// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_correctness.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *AssertRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "Assert",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *CheckResultRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CheckResult",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *CommitPrefEditsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CommitPrefEdits",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *CommitTransactionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CommitTransaction",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *DefaultLocaleRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DefaultLocale",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *NestedScrollingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NestedScrolling",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *RegisteredRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "Registered",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *SQLiteStringRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SQLiteString",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *ScrollViewCountRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ScrollViewCount",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *SetTextI18nRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SetTextI18n",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *ShiftFlagsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ShiftFlags",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *SimpleDateFormatRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SimpleDateFormat",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *StopShipRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StopShip",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *UniqueConstantsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UniqueConstants",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *WrongCallRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "WrongCall",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}

func (r *WrongThreadRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "WrongThread",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "8c7fe112712eb56a",
	}
}
