// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/style_forbidden.go
// generator: internal/codegen/cmd/krit-gen
// NOTE: Meta() for ForbiddenImportRule is hand-written in meta_forbidden_import.go.

package rules

import (
	"regexp"

	"github.com/kaeawc/krit/internal/rules/registry"
)

var _ = regexp.MustCompile

func (r *ForbiddenAnnotationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ForbiddenAnnotation",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects usage of annotations that are configured as forbidden.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "d3fd850ba6b6f360",
		Options: []registry.ConfigOption{
			{
				Name:        "annotations",
				Type:        registry.OptStringList,
				Default:     []string{"SuppressWarnings"},
				Description: "Forbidden annotation names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ForbiddenAnnotationRule).Annotations = value.([]string)
				},
			},
		},
	}
}

func (r *ForbiddenCommentRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ForbiddenComment",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects comments containing forbidden markers like TODO, FIXME, or STOPSHIP.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "d3fd850ba6b6f360",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedPatterns",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex pattern for allowed comments.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ForbiddenCommentRule).AllowedPatterns = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "comments",
				Type:        registry.OptStringList,
				Default:     []string{"TODO:", "FIXME:", "STOPSHIP:"},
				Description: "Forbidden comment markers.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ForbiddenCommentRule).Comments = value.([]string)
				},
			},
		},
	}
}

func (r *ForbiddenMethodCallRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ForbiddenMethodCall",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects calls to methods that are configured as forbidden.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "d3fd850ba6b6f360",
		Options: []registry.ConfigOption{
			{
				Name:        "methods",
				Type:        registry.OptStringList,
				Default:     []string{"print(", "println("},
				Description: "Forbidden method calls.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ForbiddenMethodCallRule).Methods = value.([]string)
				},
			},
		},
	}
}

func (r *ForbiddenNamedParamRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ForbiddenNamedParam",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects named arguments in function calls where they should not be used.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "d3fd850ba6b6f360",
		Options: []registry.ConfigOption{
			{
				Name:        "methods",
				Type:        registry.OptStringList,
				Default:     []string{"require", "check", "assert"},
				Description: "Methods where named parameters are forbidden.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ForbiddenNamedParamRule).Methods = value.([]string)
				},
			},
		},
	}
}

func (r *ForbiddenOptInRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ForbiddenOptIn",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects @OptIn annotations that opt into experimental APIs.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "d3fd850ba6b6f360",
		Options: []registry.ConfigOption{
			{
				Name:        "markerClasses",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Specific @OptIn marker classes to forbid (empty = all @OptIn).",
				Apply: func(target interface{}, value interface{}) {
					target.(*ForbiddenOptInRule).MarkerClasses = value.([]string)
				},
			},
		},
	}
}

func (r *ForbiddenSuppressRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ForbiddenSuppress",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects @Suppress annotations that silence warnings instead of fixing the underlying issue.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "d3fd850ba6b6f360",
		Options: []registry.ConfigOption{
			{
				Name:        "rules",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Specific suppressed rules to forbid (empty = all @Suppress).",
				Apply:       func(target interface{}, value interface{}) { target.(*ForbiddenSuppressRule).Rules = value.([]string) },
			},
		},
	}
}

func (r *ForbiddenVoidRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ForbiddenVoid",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects usage of the Java Void type that should be replaced with Kotlin Unit.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "d3fd850ba6b6f360",
		Options: []registry.ConfigOption{
			{
				Name:        "ignoreOverridden",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Ignore overridden functions.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ForbiddenVoidRule).IgnoreOverridden = value.(bool)
				},
			},
			{
				Name:        "ignoreUsageInGenerics",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Ignore Void in generic type arguments.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ForbiddenVoidRule).IgnoreUsageInGenerics = value.(bool)
				},
			},
		},
	}
}

func (r *MagicNumberRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MagicNumber",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects magic number literals in code that should be extracted to named constants.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "d3fd850ba6b6f360",
		Options: []registry.ConfigOption{
			{
				Name:        "ignoreAnnotated",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Annotations that suppress this rule on a declaration.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MagicNumberRule).IgnoreAnnotated = value.([]string)
				},
			},
			{
				Name:        "ignoreAnnotation",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Ignore numbers inside annotations.",
				Apply:       func(target interface{}, value interface{}) { target.(*MagicNumberRule).IgnoreAnnotation = value.(bool) },
			},
			{
				Name:        "ignoreColorLiterals",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Ignore Color(0x...) hex literals.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MagicNumberRule).IgnoreColorLiterals = value.(bool)
				},
			},
			{
				Name:        "ignoreCompanionObjectPropertyDeclaration",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Ignore numbers in companion object property declarations.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MagicNumberRule).IgnoreCompanionObjectPropertyDeclaration = value.(bool)
				},
			},
			{
				Name:        "ignoreComposeUnits",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Ignore Compose unit literals (dp, sp, em).",
				Apply: func(target interface{}, value interface{}) {
					target.(*MagicNumberRule).IgnoreComposeUnits = value.(bool)
				},
			},
			{
				Name:        "ignoreConstantDeclaration",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Ignore numbers in const val declarations.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MagicNumberRule).IgnoreConstantDeclaration = value.(bool)
				},
			},
			{
				Name:        "ignoreEnums",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Ignore numbers in enum entries.",
				Apply:       func(target interface{}, value interface{}) { target.(*MagicNumberRule).IgnoreEnums = value.(bool) },
			},
			{
				Name:        "ignoreExtensionFunctions",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Ignore numbers in extension functions.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MagicNumberRule).IgnoreExtensionFunctions = value.(bool)
				},
			},
			{
				Name:        "ignoreHashCodeFunction",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Ignore numbers in hashCode() functions.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MagicNumberRule).IgnoreHashCodeFunction = value.(bool)
				},
			},
			{
				Name:        "ignoreLocalVariableDeclaration",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Ignore numbers in local variable declarations.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MagicNumberRule).IgnoreLocalVariableDeclaration = value.(bool)
				},
			},
			{
				Name:        "ignoreNamedArgument",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Ignore numbers used as named arguments.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MagicNumberRule).IgnoreNamedArgument = value.(bool)
				},
			},
			{
				Name:        "ignoreNumbers",
				Type:        registry.OptStringList,
				Default:     []string{"-1", "0", "1", "2", "0f", "0.0f", "0.5f", "1f", "1.0f", "-1f", "90f", "180f", "270f", "360f", "100", "100f", "1000", "1000L", "10000", "10000L", "255", "255f", "60", "60f", "60L", "60000", "60000L", "24", "24L", "1024", "1024L", "16", "16f", "8", "8f", "4", "4f"},
				Description: "Numbers to ignore.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MagicNumberRule).IgnoreNumbers = value.([]string)
				},
			},
			{
				Name:        "ignorePropertyDeclaration",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Ignore numbers in property declarations.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MagicNumberRule).IgnorePropertyDeclaration = value.(bool)
				},
			},
			{
				Name:        "ignoreRanges",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Ignore numbers in range expressions.",
				Apply:       func(target interface{}, value interface{}) { target.(*MagicNumberRule).IgnoreRanges = value.(bool) },
			},
		},
	}
}

func (r *WildcardImportRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "WildcardImport",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects wildcard import statements that should be replaced with explicit imports.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "d3fd850ba6b6f360",
		Options: []registry.ConfigOption{
			{
				Name:        "excludeImports",
				Type:        registry.OptStringList,
				Default:     []string{"java.util.*"},
				Description: "Wildcard imports to exclude from this rule.",
				Apply: func(target interface{}, value interface{}) {
					target.(*WildcardImportRule).ExcludeImports = value.([]string)
				},
			},
		},
	}
}
