// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_source.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *FragmentConstructorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "FragmentConstructor",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "22bdd474ede1d1b6",
	}
}

func (r *GetSignaturesRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "GetSignatures",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "22bdd474ede1d1b6",
	}
}

func (r *LogTagLengthRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LongLogTag",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "22bdd474ede1d1b6",
	}
}

func (r *LogTagMismatchRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LogTagMismatch",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "22bdd474ede1d1b6",
	}
}

func (r *NonInternationalizedSmsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NonInternationalizedSms",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "22bdd474ede1d1b6",
	}
}

func (r *ServiceCastRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ServiceCast",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "22bdd474ede1d1b6",
	}
}

func (r *SparseArrayRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseSparseArrays",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "22bdd474ede1d1b6",
	}
}

func (r *ToastRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ShowToast",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "22bdd474ede1d1b6",
	}
}

func (r *UseValueOfRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseValueOf",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "22bdd474ede1d1b6",
	}
}
