// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/style_braces.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *BracesOnIfStatementsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "BracesOnIfStatements",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects if/else statements that are missing braces around their bodies.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		SourceHash:    "8b1aacd7ee68613e",
		Options: []registry.ConfigOption{
			{
				Name:        "multiLine",
				Type:        registry.OptString,
				Default:     "",
				Description: "Brace policy for multi-line if: never/always/necessary/consistent.",
				Apply: func(target interface{}, value interface{}) {
					target.(*BracesOnIfStatementsRule).MultiLine = value.(string)
				},
			},
			{
				Name:        "singleLine",
				Type:        registry.OptString,
				Default:     "",
				Description: "Brace policy for single-line if: never/always/necessary/consistent.",
				Apply: func(target interface{}, value interface{}) {
					target.(*BracesOnIfStatementsRule).SingleLine = value.(string)
				},
			},
		},
	}
}

func (r *BracesOnWhenStatementsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "BracesOnWhenStatements",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects when branches that are missing braces around their bodies.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		SourceHash:    "8b1aacd7ee68613e",
		Options: []registry.ConfigOption{
			{
				Name:        "multiLine",
				Type:        registry.OptString,
				Default:     "",
				Description: "Brace policy for multi-line when branches.",
				Apply: func(target interface{}, value interface{}) {
					target.(*BracesOnWhenStatementsRule).MultiLine = value.(string)
				},
			},
			{
				Name:        "singleLine",
				Type:        registry.OptString,
				Default:     "",
				Description: "Brace policy for single-line when branches.",
				Apply: func(target interface{}, value interface{}) {
					target.(*BracesOnWhenStatementsRule).SingleLine = value.(string)
				},
			},
		},
	}
}

func (r *MandatoryBracesLoopsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MandatoryBracesLoops",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects for, while, and do-while loops that are missing braces around their bodies.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		SourceHash:    "8b1aacd7ee68613e",
	}
}
