// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *ContentDescriptionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ContentDescription",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b703554f590cb527",
	}
}

func (r *ExportedServiceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExportedService",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b703554f590cb527",
	}
}

func (r *HardcodedTextRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "HardcodedText",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b703554f590cb527",
	}
}

func (r *LogDetectorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LogConditional",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b703554f590cb527",
	}
}

func (r *ObsoleteLayoutParamsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ObsoleteLayoutParam",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b703554f590cb527",
	}
}

func (r *PrivateKeyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "PackagedPrivateKey",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b703554f590cb527",
	}
}

func (r *SdCardPathRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SdCardPath",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b703554f590cb527",
	}
}

func (r *SetJavaScriptEnabledRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SetJavaScriptEnabled",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b703554f590cb527",
	}
}

func (r *ViewHolderRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ViewHolder",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b703554f590cb527",
	}
}

func (r *WakelockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "Wakelock",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b703554f590cb527",
	}
}
