// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/privacy_permissions.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *AdMobInitializedBeforeConsentRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AdMobInitializedBeforeConsent",
		RuleSet:       "privacy",
		Severity:      "warning",
		Description:   "Detects MobileAds.initialize() in Application.onCreate before any consent info update call.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1558a5b446dfabf4",
	}
}

func (r *BiometricAuthNotFallingBackToDeviceCredentialRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "BiometricAuthNotFallingBackToDeviceCredential",
		RuleSet:       "privacy",
		Severity:      "info",
		Description:   "Detects BiometricPrompt.authenticate() calls whose PromptInfo lacks device credential fallback.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1558a5b446dfabf4",
	}
}

func (r *ClipboardOnSensitiveInputTypeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ClipboardOnSensitiveInputType",
		RuleSet:       "privacy",
		Severity:      "warning",
		Description:   "Detects clipboard writes from variables whose names suggest passwords or credentials.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1558a5b446dfabf4",
	}
}

func (r *ContactsAccessWithoutPermissionUiRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ContactsAccessWithoutPermissionUi",
		RuleSet:       "privacy",
		Severity:      "warning",
		Description:   "Detects contacts queries not gated behind a RequestPermission activity-result callback.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1558a5b446dfabf4",
	}
}

func (r *LocationBackgroundWithoutRationaleRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LocationBackgroundWithoutRationale",
		RuleSet:       "privacy",
		Severity:      "warning",
		Description:   "Detects ACCESS_BACKGROUND_LOCATION requests without a shouldShowRequestPermissionRationale call.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1558a5b446dfabf4",
	}
}

func (r *ScreenshotNotBlockedOnLoginScreenRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ScreenshotNotBlockedOnLoginScreen",
		RuleSet:       "privacy",
		Severity:      "warning",
		Description:   "Detects sensitive screens (login, payment, PIN) that do not set FLAG_SECURE to block screenshots.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1558a5b446dfabf4",
	}
}
