// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/style_unnecessary.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *RedundantHigherOrderMapUsageRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "RedundantHigherOrderMapUsage",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects identity .map { it } calls that are no-ops and can be removed.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "cc154bc706023187",
	}
}

func (r *UnnecessaryAnyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryAny",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects .any { true } and .filter {}.any() patterns that can be simplified.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "cc154bc706023187",
	}
}

func (r *UnnecessaryApplyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryApply",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects .apply {} blocks that are empty or do not reference the receiver.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "cc154bc706023187",
	}
}

func (r *UnnecessaryBracesAroundTrailingLambdaRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryBracesAroundTrailingLambda",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects empty parentheses before trailing lambdas that can be removed.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "cc154bc706023187",
	}
}

func (r *UnnecessaryFilterRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryFilter",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects .filter {}.first() chains that can be simplified to .first {} with the predicate.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "cc154bc706023187",
	}
}

func (r *UnnecessaryFullyQualifiedNameRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryFullyQualifiedName",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects fully qualified names that are unnecessary because the type is already imported.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "cc154bc706023187",
	}
}

func (r *UnnecessaryLetRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryLet",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects .let {} calls that are identity transforms or single-call chains replaceable by direct invocation.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "cc154bc706023187",
	}
}

func (r *UnnecessaryReversedRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryReversed",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects chained sort and reverse calls that can be replaced with a single sort operation.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "cc154bc706023187",
	}
}
