// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/potentialbugs_types.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *AvoidReferentialEqualityRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AvoidReferentialEquality",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects usage of referential equality operators === or !== which compare object identity instead of value.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "aac7dfba23cd469a",
		Options: []registry.ConfigOption{
			{
				Name:        "forbiddenTypePatterns",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Type patterns where === is forbidden.",
				Apply: func(target interface{}, value interface{}) {
					target.(*AvoidReferentialEqualityRule).ForbiddenTypePatterns = value.([]string)
				},
			},
		},
	}
}

func (r *CharArrayToStringCallRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CharArrayToStringCall",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects charArray.toString() calls that return the array's address instead of its content.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "aac7dfba23cd469a",
	}
}

func (r *DontDowncastCollectionTypesRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DontDowncastCollectionTypes",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects downcasting read-only collection types to mutable variants like 'as MutableList'.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "aac7dfba23cd469a",
	}
}

func (r *DoubleMutabilityForCollectionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DoubleMutabilityForCollection",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects var declarations with mutable collection types, creating double mutability.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "aac7dfba23cd469a",
		Options: []registry.ConfigOption{
			{
				Name:        "mutableTypes",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Additional mutable types to check.",
				Apply: func(target interface{}, value interface{}) {
					target.(*DoubleMutabilityForCollectionRule).MutableTypes = value.([]string)
				},
			},
		},
	}
}

func (r *ElseCaseInsteadOfExhaustiveWhenRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ElseCaseInsteadOfExhaustiveWhen",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects when expressions on sealed classes or enums that use an else branch instead of exhaustive matching.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "aac7dfba23cd469a",
	}
}

func (r *EqualsAlwaysReturnsTrueOrFalseRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EqualsAlwaysReturnsTrueOrFalse",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects equals() implementations that always return true or always return false.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "aac7dfba23cd469a",
	}
}

func (r *EqualsWithHashCodeExistRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EqualsWithHashCodeExist",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects classes that override equals() without hashCode() or vice versa.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "aac7dfba23cd469a",
	}
}

func (r *ImplicitUnitReturnTypeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ImplicitUnitReturnType",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects functions with expression bodies that implicitly return Unit without an explicit return type.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "aac7dfba23cd469a",
	}
}

func (r *WrongEqualsTypeParameterRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "WrongEqualsTypeParameter",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects equals() with a parameter type other than Any?, which does not properly override the contract.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "aac7dfba23cd469a",
	}
}
