// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/exceptions.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"regexp"

	"github.com/kaeawc/krit/internal/rules/registry"
)

var _ = regexp.MustCompile

func (r *ErrorUsageWithThrowableRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ErrorUsageWithThrowable",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects error() calls that pass a Throwable argument instead of using throw directly.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
	}
}

func (r *ExceptionRaisedInUnexpectedLocationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExceptionRaisedInUnexpectedLocation",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects throw statements inside equals, hashCode, toString, or finalize methods.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
		Options: []registry.ConfigOption{
			{
				Name:        "methodNames",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Method names where exceptions are unexpected.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ExceptionRaisedInUnexpectedLocationRule).MethodNames = value.([]string)
				},
			},
		},
	}
}

func (r *InstanceOfCheckForExceptionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "InstanceOfCheckForException",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects instanceof/is checks for exception types inside catch blocks instead of using specific catch clauses.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
	}
}

func (r *NotImplementedDeclarationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NotImplementedDeclaration",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects TODO() calls that throw NotImplementedError at runtime.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
	}
}

func (r *ObjectExtendsThrowableRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ObjectExtendsThrowable",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects Kotlin object declarations that extend Throwable, which are singletons that lose stack trace information.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
	}
}

func (r *RethrowCaughtExceptionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "RethrowCaughtException",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects catch blocks whose only statement is rethrowing the caught exception, making the catch block useless.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
	}
}

func (r *ReturnFromFinallyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ReturnFromFinally",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects return statements inside finally blocks that can swallow exceptions from the try/catch.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
		Options: []registry.ConfigOption{
			{
				Name:        "ignoreLabeled",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Ignore labeled returns.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ReturnFromFinallyRule).IgnoreLabeled = value.(bool)
				},
			},
		},
	}
}

func (r *SwallowedExceptionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SwallowedException",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects catch blocks that silently swallow the caught exception without logging, handling, or rethrowing.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedExceptionNameRegex",
				Type:        registry.OptRegex,
				Default:     "^_$",
				Description: "Regex for exception names allowed to be swallowed.",
				Apply: func(target interface{}, value interface{}) {
					target.(*SwallowedExceptionRule).AllowedExceptionNameRegex = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "ignoredExceptionTypes",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Exception types allowed to be swallowed.",
				Apply: func(target interface{}, value interface{}) {
					target.(*SwallowedExceptionRule).IgnoredExceptionTypes = value.([]string)
				},
			},
		},
	}
}

func (r *ThrowingExceptionFromFinallyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ThrowingExceptionFromFinally",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects throw statements inside finally blocks that can mask exceptions from the try/catch.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
	}
}

func (r *ThrowingExceptionInMainRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ThrowingExceptionInMain",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects throw statements inside the main() function instead of graceful error handling.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
	}
}

func (r *ThrowingExceptionsWithoutMessageOrCauseRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ThrowingExceptionsWithoutMessageOrCause",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects common exception types thrown without a descriptive message or cause argument.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
		Options: []registry.ConfigOption{
			{
				Name:        "exceptions",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Exception types to check.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ThrowingExceptionsWithoutMessageOrCauseRule).Exceptions = value.([]string)
				},
			},
		},
	}
}

func (r *ThrowingNewInstanceOfSameExceptionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ThrowingNewInstanceOfSameException",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects catch blocks that throw a new instance of the same exception type instead of rethrowing the original.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "a3e49cf4d54aac54",
	}
}
