// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/potentialbugs_lifecycle.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"regexp"

	"github.com/kaeawc/krit/internal/rules/registry"
)

var _ = regexp.MustCompile

func (r *ExitOutsideMainRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExitOutsideMain",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects exitProcess() or System.exit() calls outside of the main function.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "266f1704d65385fa",
	}
}

func (r *ExplicitGarbageCollectionCallRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExplicitGarbageCollectionCall",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects explicit calls to System.gc() or Runtime.getRuntime().gc() which rarely improve performance.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "266f1704d65385fa",
	}
}

func (r *InvalidRangeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "InvalidRange",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects backwards ranges like 10..1 that produce empty ranges instead of using downTo.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "266f1704d65385fa",
	}
}

func (r *IteratorHasNextCallsNextMethodRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "IteratorHasNextCallsNextMethod",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects hasNext() implementations that call next(), which modifies iterator state.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "266f1704d65385fa",
	}
}

func (r *IteratorNotThrowingNoSuchElementExceptionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "IteratorNotThrowingNoSuchElementException",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects Iterator.next() implementations that do not throw NoSuchElementException when exhausted.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "266f1704d65385fa",
	}
}

func (r *LateinitUsageRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LateinitUsage",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects lateinit var usage and suggests lazy initialization or nullable types instead.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "266f1704d65385fa",
		Options: []registry.ConfigOption{
			{
				Name:        "ignoreOnClassesPattern",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex for classes to exclude.",
				Apply: func(target interface{}, value interface{}) {
					target.(*LateinitUsageRule).IgnoreOnClassesPattern = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *MissingPackageDeclarationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MissingPackageDeclaration",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects Kotlin files that are missing a package declaration.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.95,
		SourceHash:    "266f1704d65385fa",
	}
}

func (r *MissingSuperCallRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MissingSuperCall",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects override functions that do not call the corresponding super method.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "266f1704d65385fa",
		Options: []registry.ConfigOption{
			{
				Name:        "mustInvokeSuperAnnotations",
				Type:        registry.OptStringList,
				Default:     []string{"androidx.annotation.CallSuper", "javax.annotation.OverridingMethodsMustInvokeSuper"},
				Description: "",
				Apply: func(target interface{}, value interface{}) {
					target.(*MissingSuperCallRule).MustInvokeSuperAnnotations = value.([]string)
				},
			},
		},
	}
}

func (r *MissingUseCallRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MissingUseCall",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects Closeable or AutoCloseable resources opened without a .use {} block.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "266f1704d65385fa",
	}
}
