// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/emptyblocks.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"regexp"

	"github.com/kaeawc/krit/internal/rules/registry"
)

var _ = regexp.MustCompile

func (r *EmptyCatchBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyCatchBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects catch blocks with an empty body that silently swallow exceptions.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedExceptionNameRegex",
				Type:        registry.OptRegex,
				Default:     "^(_|ignore|expected)$",
				Description: "Regex for exception names that allow empty catch.",
				Apply: func(target interface{}, value interface{}) {
					target.(*EmptyCatchBlockRule).AllowedExceptionNameRegex = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *EmptyClassBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyClassBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects class declarations with an empty body that can have their braces removed.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptyDefaultConstructorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyDefaultConstructor",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects explicit empty default constructors that are redundant and can be removed.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptyDoWhileBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyDoWhileBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects do-while loops with an empty body.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptyElseBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyElseBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects else blocks with an empty body.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptyFinallyBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyFinallyBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects finally blocks with an empty body that serve no purpose.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptyForBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyForBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects for loops with an empty body.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptyFunctionBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyFunctionBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects function declarations with an empty body.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
		Options: []registry.ConfigOption{
			{
				Name:        "ignoreOverridden",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Ignore overridden functions with empty body.",
				Apply: func(target interface{}, value interface{}) {
					target.(*EmptyFunctionBlockRule).IgnoreOverridden = value.(bool)
				},
			},
		},
	}
}

func (r *EmptyIfBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyIfBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects if blocks with an empty body.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptyInitBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyInitBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects init blocks with an empty body that can be removed.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptyKotlinFileRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyKotlinFile",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects Kotlin files with no meaningful code beyond package and import declarations.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptySecondaryConstructorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptySecondaryConstructor",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects secondary constructors with an empty body.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptyTryBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyTryBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects try blocks with an empty body.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptyWhenBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyWhenBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects when expressions with no entries.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}

func (r *EmptyWhileBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EmptyWhileBlock",
		RuleSet:       "empty-blocks",
		Severity:      "warning",
		Description:   "Detects while loops with an empty body.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "b1d62054987b8776",
	}
}
