// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_resource_a11y.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *BackButtonResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "BackButtonResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *ButtonCaseResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ButtonCaseResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *ButtonOrderResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ButtonOrderResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *ButtonStyleResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ButtonStyleResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *ClickableViewAccessibilityResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ClickableViewAccessibilityResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *HardcodedValuesResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "HardcodedValuesResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *LabelForResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LabelForResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *LayoutAutofillHintMismatchRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LayoutAutofillHintMismatch",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *LayoutClickableWithoutMinSizeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LayoutClickableWithoutMinSize",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *LayoutEditTextMissingImportanceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LayoutEditTextMissingImportance",
		RuleSet:       "android-lint",
		Severity:      "info",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *LayoutImportantForAccessibilityNoRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LayoutImportantForAccessibilityNo",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *LayoutMinTouchTargetInButtonRowRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LayoutMinTouchTargetInButtonRow",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *MissingContentDescriptionResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MissingContentDescriptionResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *StringNotSelectableRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StringNotSelectable",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *StringRepeatedInContentDescriptionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StringRepeatedInContentDescription",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}

func (r *StringSpanInContentDescriptionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StringSpanInContentDescription",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "b7b7cd84af90d7dd",
	}
}
