// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/compose.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *ComposeColumnRowInScrollableRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeColumnRowInScrollable",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects nested same-axis scroll containers such as Column with verticalScroll containing LazyColumn.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeDerivedStateMisuseRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeDerivedStateMisuse",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects unnecessary derivedStateOf wrapping a direct boolean comparison of Compose state reads.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeDisposableEffectMissingDisposeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeDisposableEffectMissingDispose",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects DisposableEffect blocks whose body does not end with onDispose, causing resource leaks.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeLambdaCapturesUnstableStateRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeLambdaCapturesUnstableState",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects inline onClick lambdas in lazy item builders that capture the current item without hoisting through remember.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeLaunchedEffectWithoutKeysRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeLaunchedEffectWithoutKeys",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects LaunchedEffect blocks keyed only on constants whose body reads enclosing parameters that change.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeModifierBackgroundAfterClipRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeModifierBackgroundAfterClip",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects Modifier chains where background() is applied before clip(), painting outside the clip shape.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeModifierClickableBeforePaddingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeModifierClickableBeforePadding",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects Modifier chains where clickable is applied before padding, excluding the padding region from the click area.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeModifierFillAfterSizeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeModifierFillAfterSize",
		RuleSet:       "compose",
		Severity:      "info",
		Description:   "Detects Modifier chains where fillMaxWidth/Height/Size follows size(), overriding the explicit size.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeModifierPassedThenChainedRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeModifierPassedThenChained",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects @Composable functions that declare a modifier parameter but never use it, starting fresh Modifier chains instead.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeMutableDefaultArgumentRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeMutableDefaultArgument",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects @Composable parameters with mutable collection defaults that re-evaluate on each recomposition.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeMutableStateInCompositionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeMutableStateInComposition",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects mutableStateOf() used as a plain local without remember, causing state loss on every recomposition.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposePreviewAnnotationMissingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposePreviewAnnotationMissing",
		RuleSet:       "compose",
		Severity:      "info",
		Description:   "Detects @Composable functions whose name ends in Preview but lack the @Preview annotation.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposePreviewWithBackingStateRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposePreviewWithBackingState",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects @Preview functions that call runtime state holders like hiltViewModel() or collectAsState() which fail in the preview renderer.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeRememberSaveableNonParcelableRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeRememberSaveableNonParcelable",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects rememberSaveable blocks constructing non-primitive types without an explicit saver argument.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeRememberWithoutKeyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeRememberWithoutKey",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects remember blocks that reference enclosing parameters but have no keys, causing stale cached values.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeSideEffectInCompositionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeSideEffectInComposition",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects direct assignments inside @Composable function bodies that are not wrapped in a recognized effect scope.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeStatefulDefaultParameterRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeStatefulDefaultParameter",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects @Composable parameters with constructor-call defaults that allocate fresh instances every recomposition.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeStringResourceInsideLambdaRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeStringResourceInsideLambda",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects stringResource() calls inside callback lambdas where the composition-only API will crash at runtime.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}

func (r *ComposeUnstableParameterRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ComposeUnstableParameter",
		RuleSet:       "compose",
		Severity:      "warning",
		Description:   "Detects @Composable function parameters using mutable collection types that prevent recomposition skipping.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ffc8e3f0de3539e8",
	}
}
