// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_manifest_i18n.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *LocaleConfigMissingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LocaleConfigMissing",
		RuleSet:       "android-lint",
		Severity:      "info",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "05d868213ca7e1b4",
	}
}
