// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_source_extra.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *GridLayoutRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "GridLayout",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *InstantiatableRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "Instantiatable",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *LayoutInflationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LayoutInflation",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *LibraryCustomViewRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LibraryCustomView",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *LocaleFolderRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LocaleFolder",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *MangledCRLFRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MangledCRLF",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *MissingPermissionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MissingPermission",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *NfcTechWhitespaceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NfcTechWhitespace",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *ProguardRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "Proguard",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *ProguardSplitRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ProguardSplit",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *ResourceNameRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ResourceName",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *RtlAwareRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "RtlAware",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *RtlFieldAccessRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "RtlFieldAccess",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *TrulyRandomRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "TrulyRandom",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *UnknownIdInLayoutRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnknownIdInLayout",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *UseAlpha2Rule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseAlpha2",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *ViewConstructorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ViewConstructor",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *ViewTagRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ViewTag",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.85,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *WrongConstantRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "WrongConstant",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.85,
		SourceHash:    "1398771003edb0bb",
	}
}

func (r *WrongImportRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "WrongImport",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1398771003edb0bb",
	}
}
