// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_resource_values.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *ExtraTextResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExtraTextResource",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *GoogleApiKeyInResourcesRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "GoogleApiKeyInResources",
		RuleSet:       "security",
		Severity:      "warning",
		Description:   "Detects Google API keys embedded directly in XML resource files",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *ImpliedQuantityResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ImpliedQuantityResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *InconsistentArraysResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "InconsistentArraysResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *LocaleConfigStaleResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LocaleConfigStale",
		RuleSet:       "android-lint",
		Severity:      "info",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *MissingQuantityResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MissingQuantityResource",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *OnClickResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "OnClickResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *StringFormatCountResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StringFormatCountResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *StringFormatInvalidResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StringFormatInvalidResource",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *StringFormatMatchesResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StringFormatMatchesResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *StringFormatTrivialResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StringFormatTrivialResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *StringNotLocalizableResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StringNotLocalizableResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *TextFieldsResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "TextFieldsResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *UnusedAttributeResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnusedAttributeResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *UnusedQuantityResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnusedQuantityResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *WebViewInScrollViewResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "WebViewInScrollViewResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}

func (r *WrongRegionResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "WrongRegionResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "44c7ba98f90b848c",
	}
}
