// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_correctness_checks.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *AccidentalOctalRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AccidentalOctal",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *AppCompatMethodRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AppCompatMethod",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *CustomViewStyleableRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CustomViewStyleable",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *DalvikOverrideRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DalvikOverride",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *DeprecatedRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "Deprecated",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *InnerclassSeparatorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "InnerclassSeparator",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *LocalSuppressRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LocalSuppress",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *ObjectAnimatorBindingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ObjectAnimatorBinding",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *OnClickRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "OnClick",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *OverrideAbstractRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "OverrideAbstract",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *ParcelCreatorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ParcelCreator",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *PluralsCandidateRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "PluralsCandidate",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *PropertyEscapeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "PropertyEscape",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *RangeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "Range",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *ResourceAsColorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ResourceAsColor",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *ResourceTypeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ResourceType",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *ShortAlarmRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ShortAlarm",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *SupportAnnotationUsageRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SupportAnnotationUsage",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *SwitchIntDefRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SwitchIntDef",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *TextViewEditsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "TextViewEdits",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}

func (r *WrongViewCastRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "WrongViewCast",
		RuleSet:       "android-lint",
		Severity:      "",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0382b4c105c727de",
	}
}
