// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/style_expressions.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *CollapsibleIfStatementsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CollapsibleIfStatements",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects nested if statements without else that can be merged with a logical AND.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
	}
}

func (r *ExplicitItLambdaMultipleParametersRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExplicitItLambdaMultipleParameters",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects multi-parameter lambdas that use it as a parameter name.",
		DefaultActive: true,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
	}
}

func (r *ExplicitItLambdaParameterRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExplicitItLambdaParameter",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects single-parameter lambdas that explicitly name their parameter it instead of using the implicit it.",
		DefaultActive: true,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
	}
}

func (r *ExpressionBodySyntaxRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExpressionBodySyntax",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects single-expression functions that could use expression body syntax with the = operator.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
		Options: []registry.ConfigOption{
			{
				Name:        "includeLineWrapping",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Suggest expression body for multi-line returns.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ExpressionBodySyntaxRule).IncludeLineWrapping = value.(bool)
				},
			},
		},
	}
}

func (r *FunctionOnlyReturningConstantRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "FunctionOnlyReturningConstant",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects functions whose body only returns a constant value that could be a const val.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
		Options: []registry.ConfigOption{
			{
				Name:        "excludedFunctions",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Functions excluded from this rule.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FunctionOnlyReturningConstantRule).ExcludedFunctions = value.([]string)
				},
			},
			{
				Name:        "ignoreActualFunction",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Ignore actual functions.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FunctionOnlyReturningConstantRule).IgnoreActualFunction = value.(bool)
				},
			},
			{
				Name:        "ignoreOverridableFunction",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Ignore open/override functions.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FunctionOnlyReturningConstantRule).IgnoreOverridableFunction = value.(bool)
				},
			},
		},
	}
}

func (r *LoopWithTooManyJumpStatementsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LoopWithTooManyJumpStatements",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects loops containing more break or continue statements than the configured maximum.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
		Options: []registry.ConfigOption{
			{
				Name:        "maxJumpCount",
				Aliases:     []string{"threshold"},
				Type:        registry.OptInt,
				Default:     3,
				Description: "Maximum jump statements allowed in a loop.",
				Apply: func(target interface{}, value interface{}) {
					target.(*LoopWithTooManyJumpStatementsRule).MaxJumps = value.(int)
				},
			},
		},
	}
}

func (r *MayBeConstantRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MayBeConstant",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects top-level val properties with constant initializers that could be declared as const val.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
	}
}

func (r *ModifierOrderRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ModifierOrder",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects modifiers that are not in the recommended Kotlin ordering.",
		DefaultActive: true,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
	}
}

func (r *ReturnCountRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ReturnCount",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects functions with more return statements than the configured maximum.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
		Options: []registry.ConfigOption{
			{
				Name:        "excludeGuardClauses",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Exclude guard clause returns from the count.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ReturnCountRule).ExcludeGuardClauses = value.(bool)
				},
			},
			{
				Name:        "excludeLabeled",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Exclude labeled returns from the count.",
				Apply:       func(target interface{}, value interface{}) { target.(*ReturnCountRule).ExcludeLabeled = value.(bool) },
			},
			{
				Name:        "excludeReturnFromLambda",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Exclude return@lambda from the count.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ReturnCountRule).ExcludeReturnFromLambda = value.(bool)
				},
			},
			{
				Name:        "excludedFunctions",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Functions excluded from this rule.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ReturnCountRule).ExcludedFunctions = value.([]string)
				},
			},
			{
				Name:        "max",
				Aliases:     []string{"threshold"},
				Type:        registry.OptInt,
				Default:     3,
				Description: "Maximum allowed return statements.",
				Apply:       func(target interface{}, value interface{}) { target.(*ReturnCountRule).Max = value.(int) },
			},
		},
	}
}

func (r *SafeCastRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SafeCast",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects is-check followed by unsafe cast patterns that should use safe cast as? instead.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
	}
}

func (r *ThrowsCountRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ThrowsCount",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects functions with more throw statements than the configured maximum.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
		Options: []registry.ConfigOption{
			{
				Name:        "excludeGuardClauses",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Exclude guard clause throws from the count.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ThrowsCountRule).ExcludeGuardClauses = value.(bool)
				},
			},
			{
				Name:        "max",
				Aliases:     []string{"threshold"},
				Type:        registry.OptInt,
				Default:     2,
				Description: "Maximum allowed throw statements.",
				Apply:       func(target interface{}, value interface{}) { target.(*ThrowsCountRule).Max = value.(int) },
			},
		},
	}
}

func (r *VarCouldBeValRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "VarCouldBeVal",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects var properties that are never reassigned and could be declared as val.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "567378695308a4b5",
		Options: []registry.ConfigOption{
			{
				Name:        "ignoreLateinitVar",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Ignore lateinit var declarations.",
				Apply: func(target interface{}, value interface{}) {
					target.(*VarCouldBeValRule).IgnoreLateinitVar = value.(bool)
				},
			},
		},
	}
}
