// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/style_unused.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"regexp"

	"github.com/kaeawc/krit/internal/rules/registry"
)

var _ = regexp.MustCompile

func (r *UnusedImportRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnusedImport",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects import statements where the imported name is not referenced in the file.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ce9b6d2d81cbdb6b",
	}
}

func (r *UnusedParameterRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnusedParameter",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects function parameters that are never used in the function body.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ce9b6d2d81cbdb6b",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedNames",
				Type:        registry.OptRegex,
				Default:     "^(ignored|expected|_)$",
				Description: "Regex pattern for parameter names to allow.",
				Apply: func(target interface{}, value interface{}) {
					target.(*UnusedParameterRule).AllowedNames = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *UnusedPrivateClassRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnusedPrivateClass",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects private classes that are never referenced in the file.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ce9b6d2d81cbdb6b",
	}
}

func (r *UnusedPrivateFunctionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnusedPrivateFunction",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects private functions that are never called in the file.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ce9b6d2d81cbdb6b",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedNames",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex pattern for function names to allow.",
				Apply: func(target interface{}, value interface{}) {
					target.(*UnusedPrivateFunctionRule).AllowedNames = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *UnusedPrivateMemberRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnusedPrivateMember",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects private members (classes, functions, properties) that are never used.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ce9b6d2d81cbdb6b",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedNames",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex pattern for member names to allow.",
				Apply: func(target interface{}, value interface{}) {
					target.(*UnusedPrivateMemberRule).AllowedNames = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "ignoreAnnotated",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Annotations that suppress this rule.",
				Apply: func(target interface{}, value interface{}) {
					target.(*UnusedPrivateMemberRule).IgnoreAnnotated = value.([]string)
				},
			},
		},
	}
}

func (r *UnusedPrivatePropertyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnusedPrivateProperty",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects private properties that are never referenced in the file.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ce9b6d2d81cbdb6b",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedNames",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex pattern for property names to allow.",
				Apply: func(target interface{}, value interface{}) {
					target.(*UnusedPrivatePropertyRule).AllowedNames = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *UnusedVariableRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnusedVariable",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects local variables that are declared but never used.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ce9b6d2d81cbdb6b",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedNames",
				Type:        registry.OptRegex,
				Default:     "^(ignored|_)$",
				Description: "Regex pattern for variable names to allow.",
				Apply: func(target interface{}, value interface{}) {
					target.(*UnusedVariableRule).AllowedNames = value.(*regexp.Regexp)
				},
			},
		},
	}
}
