// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_icons.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *ConvertToWebpRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ConvertToWebp",
		RuleSet:       "android-lint",
		Severity:      "informational",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "8a94f9f4ae5dafb2",
	}
}

func (r *GifUsageRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "GifUsage",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "8a94f9f4ae5dafb2",
	}
}

func (r *IconDensitiesRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "IconDensities",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "8a94f9f4ae5dafb2",
	}
}

func (r *IconDipSizeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "IconDipSize",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "8a94f9f4ae5dafb2",
	}
}

func (r *IconDuplicatesConfigRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "IconDuplicatesConfig",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "8a94f9f4ae5dafb2",
	}
}

func (r *IconDuplicatesRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "IconDuplicates",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "8a94f9f4ae5dafb2",
	}
}

func (r *IconExpectedSizeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "IconExpectedSize",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "8a94f9f4ae5dafb2",
	}
}

func (r *IconMissingDensityFolderRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "IconMissingDensityFolder",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "8a94f9f4ae5dafb2",
	}
}

func (r *IconNoDpiRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "IconNoDpi",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "8a94f9f4ae5dafb2",
	}
}
