// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/potentialbugs_exceptions.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"regexp"

	"github.com/kaeawc/krit/internal/rules/registry"
)

var _ = regexp.MustCompile

func (r *PrintStackTraceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "PrintStackTrace",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects printStackTrace() calls that should use a logger instead.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "f568328627d2a58e",
	}
}

func (r *TooGenericExceptionCaughtRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "TooGenericExceptionCaught",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects catching overly generic exception types like Exception or Throwable.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f568328627d2a58e",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedExceptionNameRegex",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex for exception variable names to allow.",
				Apply: func(target interface{}, value interface{}) {
					target.(*TooGenericExceptionCaughtRule).AllowedExceptionNameRegex = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "exceptionNames",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Generic exception types to flag.",
				Apply: func(target interface{}, value interface{}) {
					target.(*TooGenericExceptionCaughtRule).ExceptionNames = value.([]string)
				},
			},
		},
	}
}

func (r *TooGenericExceptionThrownRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "TooGenericExceptionThrown",
		RuleSet:       "exceptions",
		Severity:      "warning",
		Description:   "Detects throwing overly generic exception types like Exception or Throwable.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f568328627d2a58e",
		Options: []registry.ConfigOption{
			{
				Name:        "exceptionNames",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Generic exception types to flag.",
				Apply: func(target interface{}, value interface{}) {
					target.(*TooGenericExceptionThrownRule).ExceptionNames = value.([]string)
				},
			},
		},
	}
}

func (r *UnreachableCatchBlockRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnreachableCatchBlock",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects catch blocks that are unreachable because a more general exception type is caught above.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f568328627d2a58e",
	}
}

func (r *UnreachableCodeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnreachableCode",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects code after return, throw, break, or continue statements that can never execute.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "f568328627d2a58e",
	}
}
