// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/package_naming_convention_drift.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *PackageNamingConventionDriftRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "PackageNamingConventionDrift",
		RuleSet:       "architecture",
		Severity:      "info",
		Description:   "Detects Kotlin source files whose package declaration does not match the directory path under src/main/kotlin.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "549657ebbd017d07",
	}
}
