// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_resource_style.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *AlwaysShowActionResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AlwaysShowActionResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *DisableBaselineAlignmentResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DisableBaselineAlignmentResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *InOrMmUsageResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "InOrMmUsageResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *InefficientWeightResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "InefficientWeightResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *MergeRootFrameResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MergeRootFrameResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *NegativeMarginResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NegativeMarginResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *NestedWeightsResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NestedWeightsResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *ObsoleteLayoutParamsResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ObsoleteLayoutParamsResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *OverdrawResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "OverdrawResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *PxUsageResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "PxUsageResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *SmallSpResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SmallSpResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *SpUsageResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SpUsageResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *StateListReachableResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StateListReachableResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f16d565b8a301687",
	}
}

func (r *Suspicious0dpResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "Suspicious0dpResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0,
		SourceHash:    "f16d565b8a301687",
	}
}
