// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_manifest_structure.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *DuplicateActivityManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DuplicateActivityManifest",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *DuplicateUsesFeatureManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DuplicateUsesFeatureManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *GradleOverridesManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "GradleOverridesManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *IntentFilterExportRequiredRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "IntentFilterExportRequired",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *InvalidUsesTagAttributeManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "InvalidUsesTagAttributeManifest",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *ManifestOrderManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ManifestOrderManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *ManifestTypoRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ManifestTypoManifest",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *MipmapLauncherRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MipmapLauncher",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *MissingApplicationIconRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MissingApplicationIconManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *MissingVersionManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MissingVersionManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *MockLocationManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MockLocationManifest",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *MultipleUsesSdkManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MultipleUsesSdkManifest",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *SystemPermissionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SystemPermission",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *TargetNewerRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "TargetNewer",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *UniquePermissionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UniquePermission",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *UnpackedNativeCodeManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnpackedNativeCodeManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *UsesSdkManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UsesSdkManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}

func (r *WrongManifestParentManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "WrongManifestParentManifest",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "08fa906b77f37dc0",
	}
}
