// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/privacy_storage.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *LogOfSharedPreferenceReadRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LogOfSharedPreferenceRead",
		RuleSet:       "privacy",
		Severity:      "warning",
		Description:   "Detects logger calls that directly pass SharedPreferences values with sensitive keys.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "f36dcf173ce8c985",
	}
}

func (r *PlainFileWriteOfSensitiveRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "PlainFileWriteOfSensitive",
		RuleSet:       "privacy",
		Severity:      "warning",
		Description:   "Detects plain-file writes to paths containing sensitive terms without using EncryptedFile.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "f36dcf173ce8c985",
	}
}

func (r *SharedPreferencesForSensitiveKeyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SharedPreferencesForSensitiveKey",
		RuleSet:       "privacy",
		Severity:      "warning",
		Description:   "Detects SharedPreferences put calls with key names matching sensitive patterns like token, password, or secret.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "f36dcf173ce8c985",
	}
}
