// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/package_dependency_cycle.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *PackageDependencyCycleRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "PackageDependencyCycle",
		RuleSet:       "architecture",
		Severity:      "info",
		Description:   "Detects cycles in the package-level import graph within a single Gradle module.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.95,
		Oracle:        nil,
		SourceHash:    "4c5c08492ce4dccd",
	}
}
