// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/style_classes.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *AbstractClassCanBeConcreteClassRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AbstractClassCanBeConcreteClass",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects abstract classes that have no abstract members and could be made concrete.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "e72557f1e041ba4a",
	}
}

func (r *AbstractClassCanBeInterfaceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AbstractClassCanBeInterface",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects abstract classes with no state that could be converted to interfaces.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "e72557f1e041ba4a",
	}
}

func (r *ClassOrderingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ClassOrdering",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects class members that are not in the conventional ordering of properties, init blocks, constructors, functions, and companion objects.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "e72557f1e041ba4a",
	}
}

func (r *DataClassContainsFunctionsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DataClassContainsFunctions",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects data classes that contain function members.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "e72557f1e041ba4a",
		Options: []registry.ConfigOption{
			{
				Name:        "conversionFunctionPrefix",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Prefixes for allowed conversion functions.",
				Apply: func(target interface{}, value interface{}) {
					target.(*DataClassContainsFunctionsRule).ConversionFunctionPrefix = value.([]string)
				},
			},
		},
	}
}

func (r *DataClassShouldBeImmutableRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DataClassShouldBeImmutable",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects data class properties declared as var instead of val.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "e72557f1e041ba4a",
	}
}

func (r *NestedClassesVisibilityRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NestedClassesVisibility",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects nested classes with explicit public modifier inside internal parent classes.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "e72557f1e041ba4a",
	}
}

func (r *ObjectLiteralToLambdaRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ObjectLiteralToLambda",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects object literals implementing a single method that could be converted to a lambda.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "e72557f1e041ba4a",
	}
}

func (r *OptionalAbstractKeywordRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "OptionalAbstractKeyword",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects redundant abstract modifier on interface members where it is implied.",
		DefaultActive: true,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "e72557f1e041ba4a",
	}
}

func (r *ProtectedMemberInFinalClassRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ProtectedMemberInFinalClass",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects protected members in final classes where they should be private.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "e72557f1e041ba4a",
	}
}

func (r *SerialVersionUIDInSerializableClassRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SerialVersionUIDInSerializableClass",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects Serializable classes that are missing a serialVersionUID field.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "e72557f1e041ba4a",
	}
}

func (r *UtilityClassWithPublicConstructorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UtilityClassWithPublicConstructor",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects utility classes that have a public constructor instead of a private one.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "e72557f1e041ba4a",
	}
}
