// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/privacy_analytics.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *AnalyticsCallWithoutConsentGateRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AnalyticsCallWithoutConsentGate",
		RuleSet:       "privacy",
		Severity:      "info",
		Description:   "Detects analytics event calls that are not guarded by a consent or GDPR check.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0b86c1f4b58339b7",
	}
}

func (r *AnalyticsEventWithPiiParamNameRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AnalyticsEventWithPiiParamName",
		RuleSet:       "privacy",
		Severity:      "warning",
		Description:   "Detects analytics event parameters whose key names match PII patterns like email, phone, or SSN.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0b86c1f4b58339b7",
	}
}

func (r *AnalyticsUserIdFromPiiRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AnalyticsUserIdFromPii",
		RuleSet:       "privacy",
		Severity:      "warning",
		Description:   "Detects user-ID setter calls whose argument is a PII property like email or phoneNumber.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0b86c1f4b58339b7",
	}
}

func (r *CrashlyticsCustomKeyWithPiiRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CrashlyticsCustomKeyWithPii",
		RuleSet:       "privacy",
		Severity:      "warning",
		Description:   "Detects Crashlytics setCustomKey calls where the key name matches PII patterns.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0b86c1f4b58339b7",
	}
}

func (r *FirebaseRemoteConfigDefaultsWithPiiRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "FirebaseRemoteConfigDefaultsWithPii",
		RuleSet:       "privacy",
		Severity:      "info",
		Description:   "Detects Firebase Remote Config default map keys that match PII patterns.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0b86c1f4b58339b7",
	}
}
