// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/observability.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *LogLevelGuardMissingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LogLevelGuardMissing",
		RuleSet:       "observability",
		Severity:      "info",
		Description:   "Detects debug/trace log messages with interpolated calls not guarded by a log-level check.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1d1f20e8c2716b5f",
	}
}

func (r *LogWithoutCorrelationIdRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LogWithoutCorrelationId",
		RuleSet:       "observability",
		Severity:      "info",
		Description:   "Detects logger calls inside coroutine builders whose context does not include MDCContext.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1d1f20e8c2716b5f",
	}
}

func (r *LoggerWithoutLoggerFieldRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LoggerWithoutLoggerField",
		RuleSet:       "observability",
		Severity:      "warning",
		Description:   "Detects LoggerFactory.getLogger() calls inside function bodies instead of a class-level logger field.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1d1f20e8c2716b5f",
	}
}
