// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/style_redundant.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *OptionalUnitRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "OptionalUnit",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects explicit Unit return types and return Unit statements that are redundant.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "c8800bc62687933a",
	}
}

func (r *RedundantConstructorKeywordRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "RedundantConstructorKeyword",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects unnecessary constructor keyword on primary constructors without annotations or visibility modifiers.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "c8800bc62687933a",
	}
}

func (r *RedundantExplicitTypeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "RedundantExplicitType",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects explicit type annotations that can be inferred from the initializer.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "c8800bc62687933a",
	}
}

func (r *RedundantVisibilityModifierRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "RedundantVisibilityModifier",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects explicit public modifier which is redundant since public is the default visibility in Kotlin.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "c8800bc62687933a",
	}
}

func (r *UnnecessaryBackticksRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryBackticks",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects backtick-quoted identifiers that do not require backticks.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "c8800bc62687933a",
	}
}

func (r *UnnecessaryInheritanceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryInheritance",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects unnecessary explicit inheritance from Any which is implicit in Kotlin.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "c8800bc62687933a",
	}
}

func (r *UnnecessaryInnerClassRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryInnerClass",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects inner classes that do not reference the outer class and could remove the inner modifier.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "c8800bc62687933a",
	}
}

func (r *UnnecessaryParenthesesRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryParentheses",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects unnecessary parentheses around expressions that add no value.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "c8800bc62687933a",
		Options: []registry.ConfigOption{
			{
				Name:        "allowForUnclearPrecedence",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Allow parentheses for unclear operator precedence.",
				Apply: func(target interface{}, value interface{}) {
					target.(*UnnecessaryParenthesesRule).AllowForUnclearPrecedence = value.(bool)
				},
			},
		},
	}
}

func (r *UselessCallOnNotNullRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UselessCallOnNotNull",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects calls like .orEmpty() or .isNullOrEmpty() on receivers that are already non-null.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "c8800bc62687933a",
	}
}
