// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/style_expressions_extra.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *CanBeNonNullableRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CanBeNonNullable",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects nullable types that are initialized with non-null values and never assigned null.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f7316df7ff49a697",
	}
}

func (r *DestructuringDeclarationWithTooManyEntriesRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DestructuringDeclarationWithTooManyEntries",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects destructuring declarations with more entries than the configured maximum.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f7316df7ff49a697",
		Options: []registry.ConfigOption{
			{
				Name:        "maxDestructuringEntries",
				Aliases:     []string{"threshold"},
				Type:        registry.OptInt,
				Default:     3,
				Description: "Maximum destructuring entries allowed.",
				Apply: func(target interface{}, value interface{}) {
					target.(*DestructuringDeclarationWithTooManyEntriesRule).MaxEntries = value.(int)
				},
			},
		},
	}
}

func (r *DoubleNegativeExpressionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DoubleNegativeExpression",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects double negative expressions like !isNotEmpty() that should use the positive variant.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.9,
		SourceHash:    "f7316df7ff49a697",
	}
}

func (r *DoubleNegativeLambdaRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DoubleNegativeLambda",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects double negative lambda patterns like filterNot { !predicate } that should use filter.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.9,
		SourceHash:    "f7316df7ff49a697",
		Options: []registry.ConfigOption{
			{
				Name:        "negativeFunctions",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Functions treated as negative.",
				Apply: func(target interface{}, value interface{}) {
					target.(*DoubleNegativeLambdaRule).NegativeFunctions = value.([]string)
				},
			},
		},
	}
}

func (r *MultilineLambdaItParameterRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MultilineLambdaItParameter",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects multiline lambdas that use the implicit it parameter instead of naming it explicitly.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f7316df7ff49a697",
	}
}

func (r *MultilineRawStringIndentationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MultilineRawStringIndentation",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects multiline raw strings that are missing trimIndent() or trimMargin() calls.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f7316df7ff49a697",
		Options: []registry.ConfigOption{
			{
				Name:        "indentSize",
				Type:        registry.OptInt,
				Default:     4,
				Description: "Expected indent size.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MultilineRawStringIndentationRule).IndentSize = value.(int)
				},
			},
			{
				Name:        "trimmingMethods",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Methods used for trimming.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MultilineRawStringIndentationRule).TrimmingMethods = value.([]string)
				},
			},
		},
	}
}

func (r *NullableBooleanCheckRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NullableBooleanCheck",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects equality comparisons against Boolean literals like x == true on nullable Booleans.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "f7316df7ff49a697",
	}
}

func (r *RangeUntilInsteadOfRangeToRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "RangeUntilInsteadOfRangeTo",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects usage of the until infix function that can be replaced with the ..< range operator.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "f7316df7ff49a697",
	}
}

func (r *StringShouldBeRawStringRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StringShouldBeRawString",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects string literals with many escape characters that would be more readable as raw strings.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "f7316df7ff49a697",
		Options: []registry.ConfigOption{
			{
				Name:        "maxEscapedCharacterCount",
				Aliases:     []string{"maxEscapes"},
				Type:        registry.OptInt,
				Default:     2,
				Description: "Maximum escaped characters before suggesting raw string.",
				Apply: func(target interface{}, value interface{}) {
					target.(*StringShouldBeRawStringRule).MaxEscapes = value.(int)
				},
			},
		},
	}
}

func (r *TrimMultilineRawStringRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "TrimMultilineRawString",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects multiline raw strings that should use trimIndent() or trimMargin() for proper indentation.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		SourceHash:    "f7316df7ff49a697",
		Options: []registry.ConfigOption{
			{
				Name:        "trimmingMethods",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Methods used for trimming.",
				Apply: func(target interface{}, value interface{}) {
					target.(*TrimMultilineRawStringRule).TrimmingMethods = value.([]string)
				},
			},
		},
	}
}
