// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/performance.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *ArrayPrimitiveRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ArrayPrimitive",
		RuleSet:       "performance",
		Severity:      "warning",
		Description:   "Detects Array<Int> and similar boxed primitive arrays that should use IntArray, LongArray, etc.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "6846d726ff52cb30",
	}
}

func (r *BitmapDecodeWithoutOptionsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "BitmapDecodeWithoutOptions",
		RuleSet:       "performance",
		Severity:      "warning",
		Description:   "Detects BitmapFactory.decode* calls without BitmapFactory.Options, which may decode full-size bitmaps.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "6846d726ff52cb30",
	}
}

func (r *CouldBeSequenceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CouldBeSequence",
		RuleSet:       "performance",
		Severity:      "warning",
		Description:   "Detects collection operation chains that could use sequences to avoid intermediate allocations.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "6846d726ff52cb30",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedOperations",
				Aliases:     []string{"threshold"},
				Type:        registry.OptInt,
				Default:     2,
				Description: "Minimum chained collection operations to suggest sequence.",
				Apply: func(target interface{}, value interface{}) {
					target.(*CouldBeSequenceRule).AllowedOperations = value.(int)
				},
			},
		},
	}
}

func (r *ForEachOnRangeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ForEachOnRange",
		RuleSet:       "performance",
		Severity:      "warning",
		Description:   "Detects (range).forEach patterns that should use a simple for loop to avoid lambda overhead.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "6846d726ff52cb30",
	}
}

func (r *SpreadOperatorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SpreadOperator",
		RuleSet:       "performance",
		Severity:      "warning",
		Description:   "Detects the spread operator (*array) in function calls which creates an array copy.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "6846d726ff52cb30",
	}
}

func (r *UnnecessaryInitOnArrayRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryInitOnArray",
		RuleSet:       "performance",
		Severity:      "warning",
		Description:   "Detects IntArray(n) { 0 } and similar array initializations where the init value is already the default.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "6846d726ff52cb30",
	}
}

func (r *UnnecessaryPartOfBinaryExpressionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryPartOfBinaryExpression",
		RuleSet:       "performance",
		Severity:      "warning",
		Description:   "Detects redundant parts of binary expressions like x && true or x || false.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "6846d726ff52cb30",
	}
}

func (r *UnnecessaryTemporaryInstantiationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryTemporaryInstantiation",
		RuleSet:       "performance",
		Severity:      "warning",
		Description:   "Detects temporary wrapper instantiations like Integer.valueOf(x).toString() that can be simplified.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "6846d726ff52cb30",
	}
}

func (r *UnnecessaryTypeCastingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryTypeCasting",
		RuleSet:       "performance",
		Severity:      "warning",
		Description:   "Detects redundant type casts where a value is cast to its own type.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "6846d726ff52cb30",
	}
}
