// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/database.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *DaoNotInterfaceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DaoNotInterface",
		RuleSet:       "database",
		Severity:      "info",
		Description:   "Detects Room DAOs declared as abstract classes instead of interfaces.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "d67382c415a0c063",
	}
}

func (r *DaoWithoutAnnotationsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DaoWithoutAnnotations",
		RuleSet:       "database",
		Severity:      "warning",
		Description:   "Detects Room DAO member functions missing required annotations like @Query, @Insert, @Update, or @Delete.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "d67382c415a0c063",
	}
}

func (r *DatabaseInstanceRecreatedRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DatabaseInstanceRecreated",
		RuleSet:       "resource-cost",
		Severity:      "warning",
		Description:   "Detects Room.databaseBuilder calls inside regular functions that recreate the database on each invocation.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "d67382c415a0c063",
	}
}

func (r *JdbcPreparedStatementNotClosedRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "JdbcPreparedStatementNotClosed",
		RuleSet:       "database",
		Severity:      "warning",
		Description:   "Detects JDBC prepared statements assigned to local properties without .use {} or .close() in the same scope.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "d67382c415a0c063",
	}
}
