// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/potentialbugs_properties.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *PropertyUsedBeforeDeclarationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "PropertyUsedBeforeDeclaration",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects class properties referenced in initializers or init blocks before they are declared.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0f5c02dee8c6090d",
	}
}

func (r *UnconditionalJumpStatementInLoopRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnconditionalJumpStatementInLoop",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects loops containing an unconditional return, break, or throw that causes the loop to execute only once.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0f5c02dee8c6090d",
	}
}

func (r *UnnamedParameterUseRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnamedParameterUse",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects function calls with many unnamed parameters where named parameters would improve readability.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0f5c02dee8c6090d",
		Options: []registry.ConfigOption{
			{
				Name:        "allowSingleParamUse",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Allow unnamed use of single parameter.",
				Apply: func(target interface{}, value interface{}) {
					target.(*UnnamedParameterUseRule).AllowSingleParamUse = value.(bool)
				},
			},
		},
	}
}

func (r *UnusedUnaryOperatorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnusedUnaryOperator",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects standalone unary +x or -x expressions whose result is never used.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "0f5c02dee8c6090d",
	}
}

func (r *UselessPostfixExpressionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UselessPostfixExpression",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects postfix increment or decrement in return statements where the operation has no effect.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "0f5c02dee8c6090d",
	}
}
