// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/naming.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"regexp"

	"github.com/kaeawc/krit/internal/rules/registry"
)

var _ = regexp.MustCompile

func (r *BooleanPropertyNamingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "BooleanPropertyNaming",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects Boolean properties that do not start with an allowed prefix like is, has, or are.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedPattern",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex for allowed non-standard Boolean property names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*BooleanPropertyNamingRule).AllowedPattern = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *ClassNamingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ClassNaming",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects class names that do not match the expected naming pattern.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "classPattern",
				Type:        registry.OptRegex,
				Default:     "[A-Z][a-zA-Z0-9]*",
				Description: "Regex pattern for class names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ClassNamingRule).Pattern = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *ConstructorParameterNamingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ConstructorParameterNaming",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects constructor val/var parameter names that do not match the expected naming pattern.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "excludeClassPattern",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex for classes to exclude from this rule.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ConstructorParameterNamingRule).ExcludeClassPattern = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "parameterPattern",
				Type:        registry.OptRegex,
				Default:     "[a-z][a-zA-Z0-9]*",
				Description: "Regex pattern for constructor parameter names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ConstructorParameterNamingRule).Pattern = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "privateParameterPattern",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex for private constructor parameter names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ConstructorParameterNamingRule).PrivateParameterPattern = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *EnumNamingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EnumNaming",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects enum entry names that do not match the expected naming pattern.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "enumEntryPattern",
				Type:        registry.OptRegex,
				Default:     "[A-Z][_a-zA-Z0-9]*",
				Description: "Regex pattern for enum entry names.",
				Apply:       func(target interface{}, value interface{}) { target.(*EnumNamingRule).Pattern = value.(*regexp.Regexp) },
			},
		},
	}
}

func (r *ForbiddenClassNameRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ForbiddenClassName",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects class names that match a configured list of disallowed names.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "forbiddenName",
				Type:        registry.OptStringList,
				Default:     []string{"Manager", "Helper", "Util", "Utils"},
				Description: "List of forbidden class names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ForbiddenClassNameRule).ForbiddenNames = value.([]string)
				},
			},
		},
	}
}

func (r *FunctionNameMaxLengthRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "FunctionNameMaxLength",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects function names that exceed the configured maximum length.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "maximumFunctionNameLength",
				Aliases:     []string{"maxLength"},
				Type:        registry.OptInt,
				Default:     30,
				Description: "Maximum allowed function name length.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FunctionNameMaxLengthRule).MaxLength = value.(int)
				},
			},
		},
	}
}

func (r *FunctionNameMinLengthRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "FunctionNameMinLength",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects function names that are shorter than the configured minimum length.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "minimumFunctionNameLength",
				Aliases:     []string{"minLength"},
				Type:        registry.OptInt,
				Default:     3,
				Description: "Minimum allowed function name length.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FunctionNameMinLengthRule).MinLength = value.(int)
				},
			},
		},
	}
}

func (r *FunctionNamingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "FunctionNaming",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects function names that do not match the expected naming pattern.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "excludeClassPattern",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex for classes to exclude from this rule.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FunctionNamingRule).ExcludeClassPattern = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "functionPattern",
				Type:        registry.OptRegex,
				Default:     "[a-z][a-zA-Z0-9]*",
				Description: "Regex pattern for function names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FunctionNamingRule).Pattern = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "ignoreAnnotated",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Annotations that suppress this rule.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FunctionNamingRule).IgnoreAnnotated = value.([]string)
				},
			},
		},
	}
}

func (r *FunctionParameterNamingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "FunctionParameterNaming",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects function parameter names that do not match the expected naming pattern.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "excludeClassPattern",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex for classes to exclude from this rule.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FunctionParameterNamingRule).ExcludeClassPattern = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "parameterPattern",
				Type:        registry.OptRegex,
				Default:     "[a-z][a-zA-Z0-9]*",
				Description: "Regex pattern for function parameter names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FunctionParameterNamingRule).Pattern = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *InvalidPackageDeclarationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "InvalidPackageDeclaration",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects package declarations that do not match the file directory structure.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "requireRootInDeclaration",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Require rootPackage in package declaration.",
				Apply: func(target interface{}, value interface{}) {
					target.(*InvalidPackageDeclarationRule).RequireRootInDeclaration = value.(bool)
				},
			},
			{
				Name:        "rootPackage",
				Type:        registry.OptString,
				Default:     "",
				Description: "Root package prefix to require.",
				Apply: func(target interface{}, value interface{}) {
					target.(*InvalidPackageDeclarationRule).RootPackage = value.(string)
				},
			},
		},
	}
}

func (r *LambdaParameterNamingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LambdaParameterNaming",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects lambda parameter names that do not match the expected naming pattern.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "parameterPattern",
				Type:        registry.OptRegex,
				Default:     "[a-z][a-zA-Z0-9]*",
				Description: "Regex pattern for lambda parameter names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*LambdaParameterNamingRule).Pattern = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *MatchingDeclarationNameRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MatchingDeclarationName",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects files where the single top-level declaration name does not match the filename.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "multiplatformTargets",
				Type:        registry.OptStringList,
				Default:     []string{"ios", "android", "js", "jvm", "native", "iosArm64", "iosX64", "macosX64", "mingwX64", "linuxX64"},
				Description: "Multiplatform target suffixes to strip from filename.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MatchingDeclarationNameRule).MultiplatformTargets = value.([]string)
				},
			},
			{
				Name:        "mustBeFirst",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Declaration must be first in file.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MatchingDeclarationNameRule).MustBeFirst = value.(bool)
				},
			},
		},
	}
}

func (r *MemberNameEqualsClassNameRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MemberNameEqualsClassName",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects class members whose name is the same as the containing class name.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "ignoreOverridden",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Ignore overridden members.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MemberNameEqualsClassNameRule).IgnoreOverridden = value.(bool)
				},
			},
		},
	}
}

func (r *NoNameShadowingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NoNameShadowing",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects inner declarations that shadow an outer declaration with the same name.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "4027cdddaaa2bc36",
	}
}

func (r *NonBooleanPropertyPrefixedWithIsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NonBooleanPropertyPrefixedWithIs",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects non-Boolean properties whose name starts with the is prefix.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
	}
}

func (r *ObjectPropertyNamingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ObjectPropertyNaming",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects property names inside object declarations that do not match the expected naming pattern.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "constantPattern",
				Type:        registry.OptRegex,
				Default:     "[A-Za-z][_A-Za-z0-9]*",
				Description: "Regex pattern for constant properties in objects.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ObjectPropertyNamingRule).ConstPattern = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "privatePropertyPattern",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex for private properties in objects.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ObjectPropertyNamingRule).PrivatePropertyPattern = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "propertyPattern",
				Type:        registry.OptRegex,
				Default:     "[A-Za-z][_A-Za-z0-9]*",
				Description: "Regex pattern for non-constant properties in objects.",
				Apply: func(target interface{}, value interface{}) {
					target.(*ObjectPropertyNamingRule).PropertyPattern = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *PackageNamingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "PackageNaming",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects package names that do not match the expected naming pattern.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "packagePattern",
				Type:        registry.OptRegex,
				Default:     "[a-z]+(\\.[a-z][A-Za-z0-9]*)*",
				Description: "Regex pattern for package names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*PackageNamingRule).Pattern = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *TopLevelPropertyNamingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "TopLevelPropertyNaming",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects top-level property names that do not match the expected naming pattern.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "constantPattern",
				Type:        registry.OptRegex,
				Default:     "[A-Za-z][_A-Za-z0-9]*",
				Description: "Regex pattern for top-level constant properties.",
				Apply: func(target interface{}, value interface{}) {
					target.(*TopLevelPropertyNamingRule).ConstPattern = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "privatePropertyPattern",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex for private top-level properties.",
				Apply: func(target interface{}, value interface{}) {
					target.(*TopLevelPropertyNamingRule).PrivatePropertyPattern = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "propertyPattern",
				Type:        registry.OptRegex,
				Default:     "[A-Za-z][_A-Za-z0-9]*",
				Description: "Regex pattern for top-level non-constant properties.",
				Apply: func(target interface{}, value interface{}) {
					target.(*TopLevelPropertyNamingRule).PropertyPattern = value.(*regexp.Regexp)
				},
			},
		},
	}
}

func (r *VariableMaxLengthRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "VariableMaxLength",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects variable names that exceed the configured maximum length.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "maximumVariableNameLength",
				Aliases:     []string{"maxLength"},
				Type:        registry.OptInt,
				Default:     64,
				Description: "Maximum allowed variable name length.",
				Apply:       func(target interface{}, value interface{}) { target.(*VariableMaxLengthRule).MaxLength = value.(int) },
			},
		},
	}
}

func (r *VariableMinLengthRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "VariableMinLength",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects variable names that are shorter than the configured minimum length.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "minimumVariableNameLength",
				Aliases:     []string{"minLength"},
				Type:        registry.OptInt,
				Default:     2,
				Description: "Minimum allowed variable name length.",
				Apply:       func(target interface{}, value interface{}) { target.(*VariableMinLengthRule).MinLength = value.(int) },
			},
		},
	}
}

func (r *VariableNamingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "VariableNaming",
		RuleSet:       "naming",
		Severity:      "warning",
		Description:   "Detects local variable names that do not match the expected naming pattern.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "4027cdddaaa2bc36",
		Options: []registry.ConfigOption{
			{
				Name:        "excludeClassPattern",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex for classes to exclude from this rule.",
				Apply: func(target interface{}, value interface{}) {
					target.(*VariableNamingRule).ExcludeClassPattern = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "privateVariablePattern",
				Type:        registry.OptRegex,
				Default:     "",
				Description: "Regex pattern for private variable names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*VariableNamingRule).PrivateVariablePattern = value.(*regexp.Regexp)
				},
			},
			{
				Name:        "variablePattern",
				Type:        registry.OptRegex,
				Default:     "[a-z][a-zA-Z0-9]*",
				Description: "Regex pattern for variable names.",
				Apply: func(target interface{}, value interface{}) {
					target.(*VariableNamingRule).Pattern = value.(*regexp.Regexp)
				},
			},
		},
	}
}
