// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_resource_layout.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *AdapterViewChildrenResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AdapterViewChildrenResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *IncludeLayoutParamResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "IncludeLayoutParamResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *InconsistentLayoutResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "InconsistentLayout",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *NestedScrollingResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NestedScrollingResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *OrientationResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "OrientationResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *RequiredSizeResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "RequiredSizeResource",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *ScrollViewCountResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ScrollViewCountResource",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *ScrollViewSizeResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ScrollViewSizeResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *TooDeepLayoutResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "TooDeepLayoutResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *TooManyViewsResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "TooManyViewsResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *UseCompoundDrawablesResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseCompoundDrawablesResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *UselessLeafResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UselessLeafResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}

func (r *UselessParentResourceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UselessParentResource",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "1730ca44a96d4fb4",
	}
}
