// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/security.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *ContentProviderQueryWithSelectionInterpolationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ContentProviderQueryWithSelectionInterpolation",
		RuleSet:       "security",
		Severity:      "info",
		Description:   "Detects interpolated selection strings passed to ContentResolver.query() that may enable SQL injection.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "33dc351661fdd235",
	}
}

func (r *FileFromUntrustedPathRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "FileFromUntrustedPath",
		RuleSet:       "security",
		Severity:      "info",
		Description:   "Detects File construction from untrusted input in extraction or download functions without path traversal guards.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "33dc351661fdd235",
	}
}

func (r *HardcodedBearerTokenRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "HardcodedBearerToken",
		RuleSet:       "security",
		Severity:      "warning",
		Description:   "Detects bearer authorization strings with hardcoded tokens embedded directly in source code.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "33dc351661fdd235",
	}
}

func (r *HardcodedGcpServiceAccountRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "HardcodedGcpServiceAccount",
		RuleSet:       "security",
		Severity:      "warning",
		Description:   "Detects embedded GCP service-account JSON or private keys committed into source files.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "33dc351661fdd235",
	}
}
