// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/supply_chain.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *CompileSdkMismatchAcrossModulesRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CompileSdkMismatchAcrossModules",
		RuleSet:       "supply-chain",
		Severity:      "warning",
		Description:   "Detects Android modules whose compileSdk is lower than the maximum compileSdk in the project.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "0936d0dd19e29477",
	}
}
