// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/potentialbugs_nullsafety_redundant.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *NullCheckOnMutablePropertyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NullCheckOnMutableProperty",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects null checks on mutable var properties that may be changed by another thread between the check and use.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "09c49ffe7dbb2f5a",
	}
}

func (r *NullableToStringCallRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NullableToStringCall",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects .toString() calls on nullable receivers that may produce the string \"null\".",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "09c49ffe7dbb2f5a",
	}
}

func (r *UnnecessaryNotNullCheckRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryNotNullCheck",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects unnecessary null checks on expressions that are already non-nullable.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "09c49ffe7dbb2f5a",
	}
}

func (r *UnnecessaryNotNullOperatorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessaryNotNullOperator",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects the !! operator applied to expressions that are already non-nullable.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "09c49ffe7dbb2f5a",
	}
}

func (r *UnnecessarySafeCallRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnnecessarySafeCall",
		RuleSet:       "potential-bugs",
		Severity:      "warning",
		Description:   "Detects the ?. safe-call operator applied to expressions that are already non-nullable.",
		DefaultActive: true,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "09c49ffe7dbb2f5a",
	}
}
