// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/hotspot.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *FanInFanOutHotspotRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "FanInFanOutHotspot",
		RuleSet:       "architecture",
		Severity:      "info",
		Description:   "Detects class-like declarations with unusually high fan-in across the project.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1dbc3f449cc54df5",
		Options: []registry.ConfigOption{
			{
				Name:        "allowedFanIn",
				Aliases:     []string{"threshold"},
				Type:        registry.OptInt,
				Default:     20,
				Description: "Minimum distinct external files referencing a class-like declaration before reporting it as a hotspot.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FanInFanOutHotspotRule).AllowedFanIn = value.(int)
				},
			},
			{
				Name:        "ignoreCommentReferences",
				Type:        registry.OptBool,
				Default:     true,
				Description: "Ignore references that only appear inside comments.",
				Apply: func(target interface{}, value interface{}) {
					target.(*FanInFanOutHotspotRule).IgnoreCommentReferences = value.(bool)
				},
			},
		},
	}
}

func (r *GodClassOrModuleRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "GodClassOrModule",
		RuleSet:       "architecture",
		Severity:      "warning",
		Description:   "Detects source files that import from an unusually broad set of packages, suggesting too many responsibilities.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "1dbc3f449cc54df5",
	}
}
