// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/coroutines.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *ChannelReceiveWithoutCloseRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ChannelReceiveWithoutClose",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects Channel properties in a class that are never closed, leaking the receiver coroutine.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *CollectInOnCreateWithoutLifecycleRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CollectInOnCreateWithoutLifecycle",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects Flow.collect calls in lifecycle callbacks that are not wrapped by repeatOnLifecycle.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *CollectionsSynchronizedListIterationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CollectionsSynchronizedListIteration",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects iteration over Collections.synchronized* wrappers without external synchronization.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *ConcurrentModificationIterationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ConcurrentModificationIteration",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects collection mutation inside for loops that causes ConcurrentModificationException.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *CoroutineLaunchedInTestWithoutRunTestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CoroutineLaunchedInTestWithoutRunTest",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects launch/async calls in @Test functions that are not wrapped in runTest.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *CoroutineScopeCreatedButNeverCancelledRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CoroutineScopeCreatedButNeverCancelled",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects CoroutineScope properties in a class that are never cancelled, leaking coroutines.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *DeferredAwaitInFinallyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DeferredAwaitInFinally",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects Deferred.await() calls inside finally blocks that can throw and mask the original exception.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *FlowWithoutFlowOnRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "FlowWithoutFlowOn",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects flow chains with a terminal operator but no flowOn, risking execution on the wrong dispatcher.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *GlobalCoroutineUsageRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "GlobalCoroutineUsage",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects GlobalScope.launch/async usage instead of structured concurrency with a proper CoroutineScope.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *GlobalScopeLaunchInViewModelRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "GlobalScopeLaunchInViewModel",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects GlobalScope.launch/async inside ViewModel or Presenter classes instead of viewModelScope.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *InjectDispatcherRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "InjectDispatcher",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects hardcoded Dispatchers.IO/Default/Unconfined passed as arguments instead of injected dispatchers.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
		Options: []registry.ConfigOption{
			{
				Name:        "dispatcherNames",
				Type:        registry.OptStringList,
				Default:     []string(nil),
				Description: "Dispatcher names to flag.",
				Apply: func(target interface{}, value interface{}) {
					target.(*InjectDispatcherRule).DispatcherNames = value.([]string)
				},
			},
		},
	}
}

func (r *LaunchWithoutCoroutineExceptionHandlerRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "LaunchWithoutCoroutineExceptionHandler",
		RuleSet:       "coroutines",
		Severity:      "info",
		Description:   "Detects launch blocks containing throw statements but no CoroutineExceptionHandler to catch uncaught exceptions.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *MainDispatcherInLibraryCodeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MainDispatcherInLibraryCode",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects Dispatchers.Main usage in library modules that lack the kotlinx-coroutines-android dependency.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *MutableStateInObjectRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MutableStateInObject",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects mutable var properties inside object declarations that are shared mutable state without synchronization.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *RedundantSuspendModifierRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "RedundantSuspendModifier",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects suspend functions that contain no suspend calls in their body.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *SharedFlowWithoutReplayRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SharedFlowWithoutReplay",
		RuleSet:       "coroutines",
		Severity:      "info",
		Description:   "Detects MutableSharedFlow() created with default configuration that has no replay or buffer capacity.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *SleepInsteadOfDelayRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SleepInsteadOfDelay",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects Thread.sleep() usage inside suspend functions or coroutine builder lambdas instead of delay().",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *StateFlowCompareByReferenceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StateFlowCompareByReference",
		RuleSet:       "coroutines",
		Severity:      "info",
		Description:   "Detects redundant .distinctUntilChanged() after .map{} on StateFlow, which already deduplicates by equality.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *StateFlowMutableLeakRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "StateFlowMutableLeak",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects publicly exposed MutableStateFlow properties that should be private with a read-only StateFlow accessor.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *SupervisorScopeInEventHandlerRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SupervisorScopeInEventHandler",
		RuleSet:       "coroutines",
		Severity:      "info",
		Description:   "Detects supervisorScope with a single child operation where supervisor semantics provide no benefit.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *SuspendFunInFinallySectionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SuspendFunInFinallySection",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects suspend function calls inside finally blocks that may not execute if the coroutine is cancelled.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *SuspendFunSwallowedCancellationRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SuspendFunSwallowedCancellation",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects catch blocks that catch CancellationException without rethrowing, breaking structured concurrency.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *SuspendFunWithCoroutineScopeReceiverRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SuspendFunWithCoroutineScopeReceiver",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects functions that are both suspend and extension on CoroutineScope, which should be one or the other.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *SuspendFunWithFlowReturnTypeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SuspendFunWithFlowReturnType",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects suspend functions that return a Flow type, since Flow builders are cold and do not require suspend.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *SynchronizedOnBoxedPrimitiveRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SynchronizedOnBoxedPrimitive",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects synchronized() blocks using a boxed primitive value as the lock monitor.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *SynchronizedOnNonFinalRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SynchronizedOnNonFinal",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects synchronized() blocks using a var property as the lock, which can change the monitor object.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *SynchronizedOnStringRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SynchronizedOnString",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects synchronized() blocks using a string literal as the lock monitor.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *VolatileMissingOnDclRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "VolatileMissingOnDcl",
		RuleSet:       "coroutines",
		Severity:      "warning",
		Description:   "Detects double-checked locking patterns on a var property without @Volatile annotation.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}

func (r *WithContextInSuspendFunctionNoopRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "WithContextInSuspendFunctionNoop",
		RuleSet:       "coroutines",
		Severity:      "info",
		Description:   "Detects nested withContext calls using the same dispatcher as the parent, which is redundant.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "10e1f2a14e4d81c5",
	}
}
