// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/style_idiomatic_data.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *AlsoCouldBeApplyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AlsoCouldBeApply",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects .also {} blocks with multiple it. references that could use .apply {} instead.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "c0e1ed11b73f17ef",
	}
}

func (r *EqualsNullCallRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EqualsNullCall",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects .equals(null) calls that should use == null instead.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "c0e1ed11b73f17ef",
	}
}

func (r *ExplicitCollectionElementAccessMethodRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExplicitCollectionElementAccessMethod",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects explicit .get() and .set() calls that should use index operator syntax.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "c0e1ed11b73f17ef",
	}
}

func (r *UseArrayLiteralsInAnnotationsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseArrayLiteralsInAnnotations",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects arrayOf() calls in annotations that should use array literal [] syntax.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "c0e1ed11b73f17ef",
	}
}

func (r *UseDataClassRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseDataClass",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects classes with only properties in the constructor that could be data classes.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "c0e1ed11b73f17ef",
		Options: []registry.ConfigOption{
			{
				Name:        "allowVars",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Allow classes with var properties.",
				Apply:       func(target interface{}, value interface{}) { target.(*UseDataClassRule).AllowVars = value.(bool) },
			},
		},
	}
}

func (r *UseIfEmptyOrIfBlankRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseIfEmptyOrIfBlank",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects manual isEmpty/isBlank checks that could use .ifEmpty {} or .ifBlank {} instead.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "c0e1ed11b73f17ef",
	}
}

func (r *UseIfInsteadOfWhenRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseIfInsteadOfWhen",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects when expressions with two or fewer branches that could be replaced with if.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "c0e1ed11b73f17ef",
		Options: []registry.ConfigOption{
			{
				Name:        "ignoreWhenContainingVariableDeclaration",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Ignore when with variable declarations.",
				Apply: func(target interface{}, value interface{}) {
					target.(*UseIfInsteadOfWhenRule).IgnoreWhenContainingVariableDeclaration = value.(bool)
				},
			},
		},
	}
}

func (r *UseLetRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseLet",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects null checks that could be replaced with ?.let {} scope function.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "c0e1ed11b73f17ef",
	}
}

func (r *UseSumOfInsteadOfFlatMapSizeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseSumOfInsteadOfFlatMapSize",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects flatMap/map followed by size/count/sum chains that should use sumOf instead.",
		DefaultActive: false,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "c0e1ed11b73f17ef",
	}
}
