// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/android_manifest_security.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *AllowBackupManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "AllowBackupManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *BackupRulesRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "BackupRules",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *CleartextTrafficRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CleartextTraffic",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *DebuggableManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DebuggableManifest",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *ExportedPreferenceActivityManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExportedPreferenceActivityManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *ExportedServiceManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExportedServiceManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *ExportedWithoutPermissionRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ExportedWithoutPermission",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *InsecureBaseConfigurationManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "InsecureBaseConfigurationManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *MissingExportedFlagRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MissingExportedFlag",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *ProtectedPermissionsManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ProtectedPermissionsManifest",
		RuleSet:       "android-lint",
		Severity:      "error",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *ServiceExportedManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "ServiceExportedManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *UnprotectedSMSBroadcastReceiverManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnprotectedSMSBroadcastReceiverManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *UnsafeProtectedBroadcastReceiverManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnsafeProtectedBroadcastReceiverManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}

func (r *UseCheckPermissionManifestRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseCheckPermissionManifest",
		RuleSet:       "android-lint",
		Severity:      "warning",
		Description:   "",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.75,
		Oracle:        nil,
		SourceHash:    "ed77b6516de045dc",
	}
}
