// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/deadcode.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *DeadCodeRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "DeadCode",
		RuleSet:       "dead-code",
		Severity:      "warning",
		Description:   "Detects public or internal symbols that are never referenced from any other file.",
		DefaultActive: false,
		FixLevel:      "semantic",
		Confidence:    0.75,
		SourceHash:    "e99f89be6ce1993e",
	}
}
