// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/style_format.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *CascadingCallWrappingRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "CascadingCallWrapping",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects chained calls that are not properly indented from the previous line.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "7a321ff07ffcbbc6",
		Options: []registry.ConfigOption{
			{
				Name:        "includeElvis",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Also check elvis operator chaining.",
				Apply: func(target interface{}, value interface{}) {
					target.(*CascadingCallWrappingRule).IncludeElvis = value.(bool)
				},
			},
		},
	}
}

func (r *EqualsOnSignatureLineRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "EqualsOnSignatureLine",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects expression body equals signs placed on a separate line from the function signature.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		SourceHash:    "7a321ff07ffcbbc6",
	}
}

func (r *MaxChainedCallsOnSameLineRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MaxChainedCallsOnSameLine",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects lines with more chained method calls than the configured maximum.",
		DefaultActive: false,
		FixLevel:      "",
		Confidence:    0.75,
		SourceHash:    "7a321ff07ffcbbc6",
		Options: []registry.ConfigOption{
			{
				Name:        "maxChainedCalls",
				Aliases:     []string{"threshold"},
				Type:        registry.OptInt,
				Default:     5,
				Description: "Maximum chained calls allowed on one line.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MaxChainedCallsOnSameLineRule).MaxCalls = value.(int)
				},
			},
		},
	}
}

func (r *MaxLineLengthRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "MaxLineLength",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects lines that exceed the configured maximum character length.",
		DefaultActive: true,
		FixLevel:      "",
		Confidence:    0.95,
		SourceHash:    "7a321ff07ffcbbc6",
		Options: []registry.ConfigOption{
			{
				Name:        "excludeCommentStatements",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Exclude comment lines from check.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MaxLineLengthRule).ExcludeCommentStatements = value.(bool)
				},
			},
			{
				Name:        "excludeImportStatements",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Exclude import statements from check.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MaxLineLengthRule).ExcludeImportStatements = value.(bool)
				},
			},
			{
				Name:        "excludePackageStatements",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Exclude package statements from check.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MaxLineLengthRule).ExcludePackageStatements = value.(bool)
				},
			},
			{
				Name:        "excludeRawStrings",
				Type:        registry.OptBool,
				Default:     false,
				Description: "Exclude raw string lines from check.",
				Apply: func(target interface{}, value interface{}) {
					target.(*MaxLineLengthRule).ExcludeRawStrings = value.(bool)
				},
			},
			{
				Name:        "maxLineLength",
				Aliases:     []string{"threshold"},
				Type:        registry.OptInt,
				Default:     120,
				Description: "Maximum allowed line length.",
				Apply:       func(target interface{}, value interface{}) { target.(*MaxLineLengthRule).Max = value.(int) },
			},
		},
	}
}

func (r *NewLineAtEndOfFileRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NewLineAtEndOfFile",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects files that do not end with a newline character.",
		DefaultActive: true,
		FixLevel:      "cosmetic",
		Confidence:    0.95,
		SourceHash:    "7a321ff07ffcbbc6",
	}
}

func (r *NoTabsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "NoTabs",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects tab characters used for indentation instead of spaces.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.95,
		SourceHash:    "7a321ff07ffcbbc6",
	}
}

func (r *SpacingAfterPackageAndImportsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "SpacingAfterPackageAndImports",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects missing blank lines after package and import declarations.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.95,
		SourceHash:    "7a321ff07ffcbbc6",
	}
}

func (r *TrailingWhitespaceRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "TrailingWhitespace",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects lines that end with trailing whitespace characters.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.95,
		SourceHash:    "7a321ff07ffcbbc6",
	}
}

func (r *UnderscoresInNumericLiteralsRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UnderscoresInNumericLiterals",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects large numeric literals that should use underscore separators for readability.",
		DefaultActive: false,
		FixLevel:      "cosmetic",
		Confidence:    0.75,
		SourceHash:    "7a321ff07ffcbbc6",
		Options: []registry.ConfigOption{
			{
				Name:        "acceptableLength",
				Type:        registry.OptInt,
				Default:     5,
				Description: "Acceptable numeric literal length without underscores.",
				Apply: func(target interface{}, value interface{}) {
					target.(*UnderscoresInNumericLiteralsRule).AcceptableLength = value.(int)
				},
			},
			{
				Name:        "threshold",
				Type:        registry.OptInt,
				Default:     10000,
				Description: "Alias for acceptableLength.",
				Apply: func(target interface{}, value interface{}) {
					target.(*UnderscoresInNumericLiteralsRule).Threshold = value.(int)
				},
			},
		},
	}
}
