// Code generated by krit-gen. DO NOT EDIT.
// source: internal/rules/style_idiomatic.go
// generator: internal/codegen/cmd/krit-gen

package rules

import (
	"github.com/kaeawc/krit/internal/rules/registry"
)

func (r *UseAnyOrNoneInsteadOfFindRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseAnyOrNoneInsteadOfFind",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects .find {} != null patterns that should use .any {} or .none {} instead.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "cb918d306c80b8ac",
	}
}

func (r *UseCheckNotNullRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseCheckNotNull",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects check(x != null) calls that should use checkNotNull(x) instead.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "cb918d306c80b8ac",
	}
}

func (r *UseCheckOrErrorRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseCheckOrError",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects if (!cond) throw IllegalStateException patterns that should use check().",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "cb918d306c80b8ac",
	}
}

func (r *UseEmptyCounterpartRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseEmptyCounterpart",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects listOf(), setOf(), and similar calls with no arguments that should use emptyList(), emptySet(), etc.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "cb918d306c80b8ac",
	}
}

func (r *UseIsNullOrEmptyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseIsNullOrEmpty",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects x == null || x.isEmpty() patterns that should use isNullOrEmpty().",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "cb918d306c80b8ac",
	}
}

func (r *UseOrEmptyRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseOrEmpty",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects x ?: emptyList() patterns that should use .orEmpty() instead.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "cb918d306c80b8ac",
	}
}

func (r *UseRequireNotNullRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseRequireNotNull",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects require(x != null) calls that should use requireNotNull(x) instead.",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "cb918d306c80b8ac",
	}
}

func (r *UseRequireRule) Meta() registry.RuleDescriptor {
	return registry.RuleDescriptor{
		ID:            "UseRequire",
		RuleSet:       "style",
		Severity:      "warning",
		Description:   "Detects if (!cond) throw IllegalArgumentException patterns that should use require().",
		DefaultActive: true,
		FixLevel:      "idiomatic",
		Confidence:    0.75,
		SourceHash:    "cb918d306c80b8ac",
	}
}
