package dev.jasonpearson.krit.custom

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.DataInputStream
import java.io.File

/**
 * Emits `META-INF/services/dev.jasonpearson.krit.api.KritRule` listing every
 * concrete `KritRule` implementation found in the consumer's compiled classes.
 *
 * If the consumer already ships a services file under `src/main/resources`,
 * its entries are unioned with auto-detected ones so manual registrations are
 * never lost. If both end up empty, the task writes a placeholder with a
 * comment header pointing to the docs and fails the build.
 */
@CacheableTask
abstract class KritRuleServicesTask : DefaultTask() {

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val classesDirs: ConfigurableFileCollection

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val resourcesDirs: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val outDir = outputDir.get().asFile
        outDir.deleteRecursively()
        val servicesDir = outDir.resolve("META-INF/services")
        servicesDir.mkdirs()
        val target = servicesDir.resolve(KRIT_RULE_SERVICE_NAME)

        val manualEntries = readManualServiceEntries()
        val detected = scanForKritRuleImplementations()
        val merged = (manualEntries + detected).toSortedSet()

        if (merged.isEmpty()) {
            target.writeText(EMPTY_PLACEHOLDER)
            throw IllegalStateException(
                "No `dev.jasonpearson.krit.api.KritRule` implementations found.\n" +
                    "Author a Kotlin class that implements `KritRule` (and optionally annotate it\n" +
                    "with `@KritRuleInfo`), or add an entry to\n" +
                    "  src/main/resources/META-INF/services/$KRIT_RULE_SERVICE_NAME\n" +
                    "See https://github.com/kaeawc/krit/blob/main/krit-custom-rule-plugin/README.md\n" +
                    "for a walkthrough."
            )
        }

        target.writeText(
            buildString {
                append("# Generated by dev.jasonpearson.krit.custom — do not edit.\n")
                for (entry in merged) {
                    append(entry).append('\n')
                }
            }
        )
    }

    private fun readManualServiceEntries(): Set<String> {
        val entries = linkedSetOf<String>()
        for (resourceRoot in resourcesDirs.files) {
            val file = resourceRoot.resolve("META-INF/services/$KRIT_RULE_SERVICE_NAME")
            if (!file.isFile) continue
            file.useLines { lines ->
                for (raw in lines) {
                    val line = raw.substringBefore('#').trim()
                    if (line.isNotEmpty()) {
                        entries.add(line)
                    }
                }
            }
        }
        return entries
    }

    private fun scanForKritRuleImplementations(): Set<String> {
        val byName = linkedMapOf<String, ClassInfo>()
        for (root in classesDirs.files) {
            if (!root.isDirectory) continue
            root.walkTopDown().filter { it.isFile && it.name.endsWith(".class") }.forEach { file ->
                parseClass(file)?.let { byName[it.name] = it }
            }
        }

        val memo = HashMap<String, Boolean>(byName.size * 2)
        fun implementsKritRule(name: String, seen: MutableSet<String>): Boolean {
            if (name == KRIT_RULE_INTERFACE) return true
            memo[name]?.let { return it }
            if (!seen.add(name)) return false
            val info = byName[name] ?: return false.also { memo[name] = false }
            val result = info.interfaces.any { implementsKritRule(it, seen) } ||
                (info.superName != null && info.superName != "java/lang/Object" &&
                    implementsKritRule(info.superName, seen))
            memo[name] = result
            return result
        }

        val results = sortedSetOf<String>()
        for (info in byName.values) {
            if (info.isInterface || info.isAbstract) continue
            if (implementsKritRule(info.name, linkedSetOf())) {
                results.add(info.name.replace('/', '.').replace('$', '.'))
            }
        }
        return results
    }

    private fun parseClass(file: File): ClassInfo? {
        return try {
            DataInputStream(file.inputStream().buffered()).use { input ->
                if (input.readInt() != CLASS_MAGIC) return null
                input.skipBytes(4) // minor + major version
                val poolCount = input.readUnsignedShort()
                val utf = arrayOfNulls<String>(poolCount)
                val classRef = IntArray(poolCount)
                var i = 1
                while (i < poolCount) {
                    when (input.readUnsignedByte()) {
                        CONST_UTF8 -> utf[i] = input.readUTF()
                        CONST_CLASS -> classRef[i] = input.readUnsignedShort()
                        CONST_STRING, CONST_METHOD_TYPE, CONST_MODULE, CONST_PACKAGE ->
                            input.skipBytes(2)
                        CONST_FIELDREF, CONST_METHODREF, CONST_IFACE_METHODREF,
                        CONST_NAMEANDTYPE, CONST_DYNAMIC, CONST_INVOKEDYNAMIC ->
                            input.skipBytes(4)
                        CONST_INTEGER, CONST_FLOAT -> input.skipBytes(4)
                        CONST_LONG, CONST_DOUBLE -> {
                            input.skipBytes(8)
                            i++ // long/double take two slots
                        }
                        CONST_METHODHANDLE -> input.skipBytes(3)
                        else -> return null
                    }
                    i++
                }
                val access = input.readUnsignedShort()
                val thisRef = input.readUnsignedShort()
                val superRef = input.readUnsignedShort()
                val ifaceCount = input.readUnsignedShort()
                val ifaceRefs = List(ifaceCount) { input.readUnsignedShort() }

                fun nameOf(ref: Int): String? {
                    if (ref <= 0 || ref >= poolCount) return null
                    return utf[classRef[ref]]
                }

                val thisName = nameOf(thisRef) ?: return null
                ClassInfo(
                    name = thisName,
                    superName = nameOf(superRef),
                    interfaces = ifaceRefs.mapNotNull { nameOf(it) },
                    isInterface = (access and ACC_INTERFACE) != 0,
                    isAbstract = (access and ACC_ABSTRACT) != 0,
                )
            }
        } catch (_: Exception) {
            null
        }
    }

    private data class ClassInfo(
        val name: String,
        val superName: String?,
        val interfaces: List<String>,
        val isInterface: Boolean,
        val isAbstract: Boolean,
    )

    companion object {
        const val KRIT_RULE_SERVICE_NAME = "dev.jasonpearson.krit.api.KritRule"
        private const val KRIT_RULE_INTERFACE = "dev/jasonpearson/krit/api/KritRule"

        private const val CLASS_MAGIC = 0xCAFEBABE.toInt()
        private const val CONST_UTF8 = 1
        private const val CONST_INTEGER = 3
        private const val CONST_FLOAT = 4
        private const val CONST_LONG = 5
        private const val CONST_DOUBLE = 6
        private const val CONST_CLASS = 7
        private const val CONST_STRING = 8
        private const val CONST_FIELDREF = 9
        private const val CONST_METHODREF = 10
        private const val CONST_IFACE_METHODREF = 11
        private const val CONST_NAMEANDTYPE = 12
        private const val CONST_METHODHANDLE = 15
        private const val CONST_METHOD_TYPE = 16
        private const val CONST_DYNAMIC = 17
        private const val CONST_INVOKEDYNAMIC = 18
        private const val CONST_MODULE = 19
        private const val CONST_PACKAGE = 20

        private const val ACC_INTERFACE = 0x0200
        private const val ACC_ABSTRACT = 0x0400

        private val EMPTY_PLACEHOLDER = (
            "# Generated by dev.jasonpearson.krit.custom — no rules were registered.\n" +
                "# Add a class that implements dev.jasonpearson.krit.api.KritRule and rebuild,\n" +
                "# or list fully-qualified rule class names below (one per line).\n" +
                "# See: https://github.com/kaeawc/krit/blob/main/krit-custom-rule-plugin/README.md\n"
            )
    }
}
