package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/kaeawc/krit/internal/onboarding"
)

// TestInitSubcommandHeadless exercises the bubbletea TUI subcommand's
// non-interactive code path (--profile NAME --yes). The interactive
// bubbletea model requires a TTY and cannot run under `go test`, so
// this test covers everything below the UI layer: the onboarding
// package, the subcommand arg parsing, and the config write-out.
func TestInitSubcommandHeadless(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in -short mode")
	}

	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}

	playgrounds := []string{"android-app", "kotlin-webservice"}
	profiles := []string{"strict", "balanced", "relaxed", "detekt-compat"}

	for _, pg := range playgrounds {
		for _, profile := range profiles {
			pg, profile := pg, profile
			t.Run(pg+"/"+profile, func(t *testing.T) {
				src := filepath.Join(repoRoot, "playground", pg)
				if _, err := os.Stat(src); err != nil {
					t.Skipf("playground %s missing: %v", pg, err)
				}

				target := t.TempDir()
				copyDir(t, src, target)
				_ = os.Remove(filepath.Join(target, "krit.yml"))
				_ = os.RemoveAll(filepath.Join(target, ".krit"))

				cmd := exec.Command(binPath, "init", "--profile", profile, "--yes", target)
				cmd.Env = append(os.Environ(), "KRIT_BIN="+binPath, "KRIT_REPO_ROOT="+repoRoot)
				out, err := cmd.CombinedOutput()
				if err != nil {
					t.Fatalf("krit init failed: %v\n%s", err, out)
				}

				configPath := filepath.Join(target, "krit.yml")
				if _, err := os.Stat(configPath); err != nil {
					t.Fatalf("krit.yml not created: %v", err)
				}
				body, err := os.ReadFile(configPath)
				if err != nil {
					t.Fatalf("reading krit.yml: %v", err)
				}
				if !strings.HasPrefix(string(body), "# Generated by krit init (bubbletea TUI)") {
					t.Errorf("krit.yml missing TUI header prefix; first bytes: %q", string(body[:80]))
				}

				// The subcommand should also produce a summary line on stdout.
				if !strings.Contains(string(out), "wrote ") {
					t.Errorf("expected `wrote ...` summary in stdout; got: %q", out)
				}
				if !strings.Contains(string(out), "baseline written to ") {
					t.Errorf("expected `baseline written to ...` in stdout; got: %q", out)
				}

				// Validate the generated config with --validate-config
				// to guard against drift between the TUI-generated YAML
				// and krit's schema.
				vcmd := exec.Command(binPath, "--validate-config", "--config", configPath)
				if vout, err := vcmd.CombinedOutput(); err != nil {
					t.Errorf("--validate-config failed: %v\n%s", err, vout)
				} else if !strings.Contains(string(vout), "validation passed") {
					t.Errorf("validate-config did not pass; output: %s", vout)
				}

				// Baseline should exist after the headless flow runs.
				baselinePath := filepath.Join(target, ".krit", "baseline.xml")
				if _, err := os.Stat(baselinePath); err != nil {
					t.Errorf("baseline not created: %v", err)
				}
			})
		}
	}
}

// TestQuestionnaireViewRendersFixture builds an initModel in the
// questionnaire phase and drives the View() function directly, so
// the live code preview can be asserted without a TTY.
func TestQuestionnaireViewRendersFixture(t *testing.T) {
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}

	reg, err := onboardingLoadRegistryForTest(t, repoRoot)
	if err != nil {
		t.Fatal(err)
	}

	m := newInitModel(onboarding.ScanOptions{RepoRoot: repoRoot}, reg, repoRoot, "", false)
	m.width = 160
	m.height = 40
	m.selected = "balanced"
	// Seed a fake scan result so the live total line renders.
	m.scans["balanced"] = &onboarding.ScanResult{Total: 42, ByRule: map[string]int{}}
	m.startQuestionnaire()
	// Fixtures are loaded asynchronously; execute the Cmd inline for tests.
	cmd := loadFixturesCmd(m.registry.Questions, m.opts.RepoRoot)
	msg := cmd().(fixturesLoadedMsg)
	for k, v := range msg.cache {
		m.fixtureCache[k] = v
	}
	m.syncFixtureViewport()

	if m.phase != phaseQuestionnaire {
		t.Fatalf("phase = %v, want questionnaire", m.phase)
	}
	if len(m.fixtureCache) == 0 {
		t.Fatal("fixture cache was not populated")
	}

	out := m.View()
	if !strings.Contains(out, "krit init — questionnaire") {
		t.Errorf("view missing title: %s", snippet(out, 200))
	}
	// The first question ("strict-null-safety") is a parent that
	// cascades to children with fixtures. The preview should show
	// the first child's fixture content or "rule disabled", not
	// "no fixture".
	hasContent := strings.Contains(out, "rule disabled") ||
		strings.Contains(out, "package") ||
		strings.Contains(out, "fun ") ||
		strings.Contains(out, "class ")
	if !hasContent {
		t.Errorf("view missing fixture content: %s", snippet(out, 400))
	}
}

// TestQuestionnaireViewToggleNegative verifies the t/tab key toggles
// the fixture preview between positive and negative.
func TestQuestionnaireViewToggleNegative(t *testing.T) {
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}

	reg, err := onboardingLoadRegistryForTest(t, repoRoot)
	if err != nil {
		t.Fatal(err)
	}

	m := newInitModel(onboarding.ScanOptions{RepoRoot: repoRoot}, reg, repoRoot, "", false)
	m.width = 160
	m.height = 40
	m.selected = "balanced"
	m.scans["balanced"] = &onboarding.ScanResult{Total: 42, ByRule: map[string]int{}}
	m.startQuestionnaire()

	// Advance past parent questions until we're on a rule question
	// with a real fixture.
	for i := 0; i < len(m.visibleQs); i++ {
		q := &reg.Questions[m.visibleQs[i]]
		if q.PositiveFixture != nil {
			m.qIdx = i
			break
		}
	}

	q := &reg.Questions[m.visibleQs[m.qIdx]]
	if q.PositiveFixture == nil {
		t.Skip("no rule question with positive fixture found in registry")
	}

	// Yes → rule active → should show diff.
	m.qCursor = 0
	yesView := m.View()

	// No → rule inactive → should show "rule disabled".
	m.qCursor = 1
	noView := m.View()

	if yesView == noView {
		t.Error("switching yes/no did not change the fixture preview")
	}
}

// onboardingLoadRegistryForTest loads the registry from the known
// repo path and makes any test failure actionable.
func onboardingLoadRegistryForTest(t *testing.T, repoRoot string) (*onboarding.Registry, error) {
	t.Helper()
	return onboarding.LoadRegistry(filepath.Join(repoRoot, "config", "onboarding", "controversial-rules.json"))
}

func snippet(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

// TestExplorerPhasePopulatesAndToggles builds an initModel, enters
// the explorer phase, toggles one rule, and verifies the rendered
// view reflects the change. Does not go all the way to writing the
// config file — that path is exercised by the main subcommand tests.
func TestExplorerPhasePopulatesAndToggles(t *testing.T) {
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}

	reg, err := onboardingLoadRegistryForTest(t, repoRoot)
	if err != nil {
		t.Fatal(err)
	}

	m := newInitModel(onboarding.ScanOptions{RepoRoot: repoRoot}, reg, repoRoot, "", false)
	m.width = 160
	m.height = 40
	m.selected = "balanced"
	m.scans["balanced"] = &onboarding.ScanResult{
		Total:  10,
		ByRule: map[string]int{"MagicNumber": 10},
	}
	m.startExplorer()

	if m.phase != phaseExplorer {
		t.Fatalf("phase = %v, want explorer", m.phase)
	}
	if len(m.ruleItems) == 0 {
		t.Fatal("ruleItems not populated from registry")
	}
	// MagicNumber should be in the list and live-counted.
	found := false
	for i, item := range m.ruleItems {
		if item.name == "MagicNumber" {
			if item.count != 10 {
				t.Errorf("MagicNumber count = %d, want 10", item.count)
			}
			m.explorerCursor = i
			found = true
			break
		}
	}
	if !found {
		t.Fatal("MagicNumber not found in ruleItems")
	}

	// Initial live total matches the scan total (no toggles yet).
	if m.liveTotal != 10 {
		t.Errorf("liveTotal = %d, want 10", m.liveTotal)
	}

	// Simulate pressing space to toggle MagicNumber off.
	mInterface, _ := m.updateExplorer(tea.KeyMsg{Type: tea.KeySpace})
	m2 := mInterface.(initModel)
	if m2.ruleActive["MagicNumber"] != false {
		t.Error("expected MagicNumber to be toggled off after space")
	}
	if m2.liveTotal != 0 {
		t.Errorf("liveTotal after toggle = %d, want 0 (10 - 10)", m2.liveTotal)
	}
}

// TestInitSubcommandInvalidProfile confirms argument validation
// returns a non-zero exit without touching the filesystem.
func TestInitSubcommandInvalidProfile(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in -short mode")
	}

	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}

	target := t.TempDir()
	cmd := exec.Command(binPath, "init", "--profile", "bogus", "--yes", target)
	cmd.Env = append(os.Environ(), "KRIT_BIN="+binPath, "KRIT_REPO_ROOT="+repoRoot)
	out, err2 := cmd.CombinedOutput()
	err = err2
	if err == nil {
		t.Errorf("expected non-zero exit for invalid profile; stdout: %s", out)
	}
	if !strings.Contains(string(out), "unknown profile") {
		t.Errorf("expected 'unknown profile' in stderr, got: %q", out)
	}
	if _, err := os.Stat(filepath.Join(target, "krit.yml")); err == nil {
		t.Error("krit.yml should not be created when --profile is invalid")
	}
}
