package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// requireExternalDeps skips the test unless bash + gum + jq + yq are
// all present. The krit-init onboarding script is a bash/gum
// prototype; machines without those tools cannot run these tests.
func requireExternalDeps(t *testing.T) {
	t.Helper()
	for _, bin := range []string{"bash", "gum", "jq", "yq"} {
		if _, err := exec.LookPath(bin); err != nil {
			t.Skipf("%s not installed; skipping krit-init integration tests", bin)
		}
	}
}

// copyDir performs a recursive copy from src to dst, preserving
// permissions on regular files. It is only used here to stage a
// throwaway copy of a playground project for each integration run.
func copyDir(t *testing.T, src, dst string) {
	t.Helper()
	err := filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, info.Mode())
	})
	if err != nil {
		t.Fatalf("copyDir %s -> %s: %v", src, dst, err)
	}
}

// runKritInit runs scripts/krit-init.sh against a staged target with
// the given profile, in non-interactive mode. Returns stdout+stderr
// so the caller can inspect output on failure.
func runKritInit(t *testing.T, repoRoot, target, profile string) (string, error) {
	t.Helper()
	script := filepath.Join(repoRoot, "scripts", "krit-init.sh")
	cmd := exec.Command("bash", script, "--profile", profile, "--yes", target)
	cmd.Env = append(os.Environ(), "KRIT_BIN="+binPath)
	out, err := cmd.CombinedOutput()
	return string(out), err
}

// assertOnboardingArtifacts checks that krit.yml and .krit/baseline.xml
// exist in the target and that krit.yml starts with the init header
// (so we know it came from the script, not a pre-existing file).
func assertOnboardingArtifacts(t *testing.T, target string) {
	t.Helper()

	configPath := filepath.Join(target, "krit.yml")
	if _, err := os.Stat(configPath); err != nil {
		t.Fatalf("krit.yml not created: %v", err)
	}
	header, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("reading krit.yml: %v", err)
	}
	if !strings.HasPrefix(string(header), "# Generated by scripts/krit-init.sh") {
		t.Errorf("krit.yml missing generated-header prefix; got %q", string(header[:80]))
	}

	baselinePath := filepath.Join(target, ".krit", "baseline.xml")
	if _, err := os.Stat(baselinePath); err != nil {
		t.Errorf("baseline.xml not created: %v", err)
	}
}

// TestKritInitPlaygroundEndToEnd runs scripts/krit-init.sh against a
// throwaway copy of each playground project with each of the four
// shipped profiles. Each run must exit 0 and produce both krit.yml
// and .krit/baseline.xml. Mutations (autofix) only touch the copied
// target, never the source playground.
func TestKritInitPlaygroundEndToEnd(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in -short mode")
	}
	requireExternalDeps(t)

	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}

	// Assert the krit-init script exists and is executable. On a
	// fresh checkout it will be checked in with +x, but this guards
	// against a regression in the repo metadata.
	script := filepath.Join(repoRoot, "scripts", "krit-init.sh")
	if info, err := os.Stat(script); err != nil {
		t.Fatalf("krit-init.sh missing: %v", err)
	} else if info.Mode()&0o111 == 0 {
		t.Fatalf("krit-init.sh is not executable: mode %v", info.Mode())
	}

	playgrounds := []string{"android-app", "kotlin-webservice"}
	profiles := []string{"strict", "balanced", "relaxed", "detekt-compat"}

	for _, pg := range playgrounds {
		for _, profile := range profiles {
			pg, profile := pg, profile
			t.Run(pg+"/"+profile, func(t *testing.T) {
				src := filepath.Join(repoRoot, "playground", pg)
				if _, err := os.Stat(src); err != nil {
					t.Skipf("playground %s missing: %v", pg, err)
				}

				target := t.TempDir()
				copyDir(t, src, target)

				// Strip any pre-existing config so we exercise the
				// greenfield path. The script moves existing files
				// aside, but a clean slate is closer to what a real
				// user sees.
				_ = os.Remove(filepath.Join(target, "krit.yml"))
				_ = os.RemoveAll(filepath.Join(target, ".krit"))

				out, err := runKritInit(t, repoRoot, target, profile)
				if err != nil {
					t.Fatalf("krit-init failed: %v\n%s", err, out)
				}
				assertOnboardingArtifacts(t, target)
			})
		}
	}
}

// TestKritInitGreenfield verifies the "empty project" path: a brand
// new directory with a single trivial Kotlin file should produce a
// valid krit.yml and a (possibly empty) baseline.
func TestKritInitGreenfield(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in -short mode")
	}
	requireExternalDeps(t)

	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}

	target := t.TempDir()
	hello := filepath.Join(target, "Hello.kt")
	if err := os.WriteFile(hello, []byte("fun main() { println(\"hi\") }\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	out, err := runKritInit(t, repoRoot, target, "strict")
	if err != nil {
		t.Fatalf("krit-init greenfield failed: %v\n%s", err, out)
	}
	assertOnboardingArtifacts(t, target)
}
